# column_width = 120
# line_endings = "Unix"
# indent_type = "Tabs" | "Spaces"
# indent_width = 4
# quote_style = "AutoPreferDouble" | "AutoPreferSingle" | "ForceDouble" | "ForceSingle"
# call_parentheses = "Always" | "NoSingleString" | "NoSingleTable" | "None"
# collapse_simple_statement = "Never" | "FunctionOnly" | "ConditionalOnly" | "Always"
