local settings = {
	icons = {
		aerial = {
			Array = " ",
			Boolean = " ",
			Class = " ",
			Color = " ",
			Constant = " ",
			Constructor = " ",
			Enum = " ",
			EnumMember = " ",
			Event = " ",
			Field = " ",
			File = " ",
			Folder = " ",
			Function = " ",
			Interface = " ",
			Key = " ",
			Keyword = " ",
			Method = " ",
			Module = " ",
			Namespace = " ",
			Null = "ﳠ ",
			Number = " ",
			Object = " ",
			Operator = " ",
			Package = " ",
			Property = " ",
			Reference = " ",
			Snippet = " ",
			String = " ",
			Struct = " ",
			Text = " ",
			TypeParameter = " ",
			Unit = " ",
			Value = " ",
			Variable = " ",
		},
		dap = {
			Breakpoint = "● ",
			BreakpointRejected = " ",
			BreakpointCondition = " ",
			BreakpointLog = "● ",
			Stopped = " ",
		},
		diagnostics = {
			Error = " ",
			Warn = " ",
			Hint = " ",
			Info = " ",
		},
		kinds = {
			Text = "",
			Method = "",
			Function = "",
			Constructor = "",
			Field = "",
			Variable = "",
			Class = "",
			Interface = "",
			Module = "",
			Property = "",
			Unit = "",
			Value = "",
			Enum = "",
			Keyword = "",
			Snippet = "",
			Color = "",
			File = "",
			Reference = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
	},
	ft_exclude = {
		"aerial",
		"alpha",
		"checkhealth",
		"dap-repl",
		"help",
		"lazy",
		"lspinfo",
		"lspsagafinder",
		"lspsagaoutline",
		"markdown",
		"mason",
		"neo-tree",
		"norg",
		"Trouble",
	},
	ms_install = {
		"black",
		"debugpy",
		"markdownlint",
		"prettierd",
		"stylua",
		"tectonic",
	},
	ts_install = {
		"bash",
		"bibtex",
		"diff",
		"fish",
		"latex",
		"markdown",
		"markdown_inline",
		"python",
		"query",
		"regex",
		"swift",
	},
}

return settings
