local colors = {}

---@class LazyVimSettings
local settings = {
	icons = {
		aerial = {
			Array = " ",
			Boolean = " ",
			Class = " ",
			Color = " ",
			Constant = " ",
			Constructor = " ",
			Enum = " ",
			EnumMember = " ",
			Event = " ",
			Field = " ",
			File = " ",
			Folder = " ",
			Function = " ",
			Interface = " ",
			Key = " ",
			Keyword = " ",
			Method = " ",
			Module = " ",
			Namespace = " ",
			Null = "ﳠ ",
			Number = " ",
			Object = " ",
			Operator = " ",
			Package = " ",
			Property = " ",
			Reference = " ",
			Snippet = " ",
			String = " ",
			Struct = " ",
			Text = " ",
			TypeParameter = " ",
			Unit = " ",
			Value = " ",
			Variable = " ",
		},
		dap = {
			Breakpoint = "● ",
			BreakpointRejected = " ",
			BreakpointCondition = " ",
			BreakpointLog = "● ",
			Stopped = " ",
		},
		diagnostics = {
			Error = " ",
			Warn = " ",
			Hint = " ",
			Info = " ",
		},
		kinds = {
			Text = "",
			Method = "",
			Function = "",
			Constructor = "",
			Field = "",
			Variable = "",
			Class = "",
			Interface = "",
			Module = "",
			Property = "",
			Unit = "",
			Value = "",
			Enum = "",
			Keyword = "",
			Snippet = "",
			Color = "",
			File = "",
			Reference = "",
			Folder = "",
			EnumMember = "",
			Constant = "",
			Struct = "",
			Event = "",
			Operator = "",
			TypeParameter = "",
		},
		saga = {
			[1] = { "File", " ", colors.fg },
			[2] = { "Module", " ", colors.blue },
			[3] = { "Namespace", " ", colors.orange },
			[4] = { "Package", " ", colors.violet },
			[5] = { "Class", " ", colors.violet },
			[6] = { "Method", " ", colors.violet },
			[7] = { "Property", " ", colors.cyan },
			[8] = { "Field", " ", colors.teal },
			[9] = { "Constructor", " ", colors.blue },
			[10] = { "Enum", "了", colors.green },
			[11] = { "Interface", " ", colors.orange },
			[12] = { "Function", " ", colors.violet },
			[13] = { "Variable", " ", colors.blue },
			[14] = { "Constant", " ", colors.cyan },
			[15] = { "String", " ", colors.green },
			[16] = { "Number", " ", colors.green },
			[17] = { "Boolean", " ", colors.orange },
			[18] = { "Array", " ", colors.blue },
			[19] = { "Object", " ", colors.orange },
			[20] = { "Key", " ", colors.red },
			[21] = { "Null", " ", colors.red },
			[22] = { "EnumMember", " ", colors.green },
			[23] = { "Struct", " ", colors.violet },
			[24] = { "Event", " ", colors.violet },
			[25] = { "Operator", " ", colors.green },
			[26] = { "TypeParameter", " ", colors.green },
			-- ccls
			[252] = { "TypeAlias", " ", colors.green },
			[253] = { "Parameter", " ", colors.blue },
			[254] = { "StaticMethod", "ﴂ ", colors.orange },
			[255] = { "Macro", " ", colors.red },
			-- for completion sb microsoft!!!
			[300] = { "Text", " ", colors.green },
			[301] = { "Snippet", " ", colors.blue },
			[302] = { "Folder", " ", colors.yellow },
			[303] = { "Unit", " ", colors.cyan },
			[304] = { "Value", " ", colors.blue },
		},
		lspsaga = {
			File = { " ", "#D4D4D4" },
			Module = { " ", "#D4D4D4" },
			Namespace = { " ", "#4EC9B0" },
			Package = { " ", "#C586C0" },
			Class = { " ", "#f28b25" },
			Method = { " ", "#C586C0" },
			Property = { " ", "#9CDCFE" },
			Field = { " ", "#4EC9B0" },
			Constructor = { " ", "#4EC9B0" },
			Enum = { " ", "#4EC9B0" },
			Interface = { " ", "#9CDCFE" },
			Function = { " ", "#C586C0" },
			Variable = { " ", "#9CDCFE" },
			Constant = { " ", "#569CD6" },
			String = { " ", "#4EC9B0" },
			Number = { " ", "#B5CEA8" },
			Boolean = { " ", "#569CD6" },
			Array = { " ", "#569CD6" },
			Object = { " ", "#CE9178" },
			Key = { " ", "#D4D4D4" },
			Null = { "ﳠ ", "#F44747" },
			EnumMember = { " ", "#4EC9B0" },
			Struct = { " ", "#569CD6" },
			Event = { " ", "#DCDCAA" },
			Operator = { " ", "#D4D4D4" },
			TypeParameter = { " ", "#9CDCFE" },
			-- ccls
			TypeAlias = { "ﰠ ", "#4EC9B0" },
			Parameter = { " ", "#569CD6" },
			StaticMethod = { " ", "#6A9955" },
			Macro = { " ", "#F44747" },
		},
	},
	ft_exclude = {
		"aerial",
		"alpha",
		"checkhealth",
		"dap-repl",
		"help",
		"lazy",
		"lspinfo",
		"lspsagafinder",
		"lspsagaoutline",
		"markdown",
		"mason",
		"neo-tree",
		"norg",
		"Trouble",
	},
	ms_install = {
		"black",
		"debugpy",
		"markdownlint",
		"prettierd",
		"stylua",
		"tectonic",
	},
	ts_install = {
		"bash",
		"bibtex",
		"diff",
		"fish",
		"latex",
		"markdown",
		"markdown_inline",
		"python",
		"query",
		"regex",
		"swift",
	},
}

return settings
