vim.g.colors_name = 'catppuccin'

vim.g.terminal_color_15 = '#D9E0EE'
vim.g.terminal_color_7 = '#D9E0EE'
vim.g.terminal_color_5 = '#F5C2E7'
vim.g.terminal_color_2 = '#ABE9B3'
vim.g.terminal_color_0 = '#6E6C7E'
vim.g.terminal_color_3 = '#FAE3B0'
vim.g.terminal_color_10 = '#ABE9B3'
vim.g.terminal_color_13 = '#F5C2E7'
vim.g.terminal_color_14 = '#89DCEB'
vim.g.terminal_color_6 = '#89DCEB'
vim.g.terminal_color_4 = '#96CDFB'
vim.g.terminal_color_11 = '#FAE3B0'
vim.g.terminal_color_12 = '#96CDFB'
vim.g.terminal_color_1 = '#F28FAD'
vim.g.terminal_color_9 = '#F28FAD'
vim.g.terminal_color_8 = '#988BA2'

vim.api.nvim_set_hl(0, 'NotifyERRORTitle', { fg = '#F28FAD', italic = true })
vim.api.nvim_set_hl(0, 'NormalNC', { bg = '#1E1E2E', fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'SpellCap', { sp = '#FAE3B0', undercurl = true })
vim.api.nvim_set_hl(0, 'NeoTreeTabSeparatorActive', { bg = '#1A1826', fg = '#1A1826' })
vim.api.nvim_set_hl(0, '@keyword.return', { fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, '@text.literal', { italic = true, fg = '#B5E8E0' })
vim.api.nvim_set_hl(0, 'SpellLocal', { sp = '#96CDFB', undercurl = true })
vim.api.nvim_set_hl(0, 'Substitute', { bg = '#45475A', fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, '@function', { fg = '#96CDFB', italic = true, bold = true })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'Boolean', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { fg = '#B5E8E0' })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, '@text.environment', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#6E6C7E' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#1E1E2E', fg = '#45475A' })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = '#45475A' })
vim.api.nvim_set_hl(0, '@parameter', { italic = true, fg = '#F5E0DC' })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#CDCFFF' })
vim.api.nvim_set_hl(0, '@constructor.lua', { fg = '#F2CDCD' })
vim.api.nvim_set_hl(0, 'CmpItemKind', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'Visual', { bold = true, bg = '#45475A' })
vim.api.nvim_set_hl(0, 'NeoTreeGitAdded', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, '@keyword', { italic = true, fg = '#DDB6F2' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBorder', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'rainbowcol4', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, '@conditional', { italic = true, fg = '#DDB6F2' })
vim.api.nvim_set_hl(0, 'Float', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, '@repeat', { bold = true, fg = '#DDB6F2' })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'AerialPackageIcon', { link = '@namespace' })
vim.api.nvim_set_hl(0, 'NeoTreeIndentMarker', { fg = '#6E6C7E' })
vim.api.nvim_set_hl(0, 'AerialObjectIcon', { link = '@type' })
vim.api.nvim_set_hl(0, '@text.strike', { strikethrough = true })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = '#1E1E2E' })
vim.api.nvim_set_hl(0, 'AerialFunctionIcon', { link = '@function' })
vim.api.nvim_set_hl(0, 'NeoTreeGitConflict', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'AerialStringIcon', { link = '@string' })
vim.api.nvim_set_hl(0, '@include', { fg = '#B5E8E0' })
vim.api.nvim_set_hl(0, 'Debug', { link = 'Special' })
vim.api.nvim_set_hl(0, '@boolean', { fg = '#F8BD96', italic = true, bold = true })
vim.api.nvim_set_hl(0, 'CmpItemAbbr', { fg = '#C3BAC6' })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#DDB6F2' })
vim.api.nvim_set_hl(0, 'NotifyINFOTitle', { fg = '#96CDFB', italic = true })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#CDCFFF' })
vim.api.nvim_set_hl(0, 'AerialModuleIcon', { link = '@namespace' })
vim.api.nvim_set_hl(0, 'Label', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, '@tag.attribute', { italic = true, fg = '#DDB6F2' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'AerialMethodIcon', { link = '@method' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, 'NeoTreeNormal', { bg = '#1A1826', fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'FoldColumn', { bg = '#1E1E2E', fg = '#6E6C7E' })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, '@type', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'NotifyTRACEIcon', { fg = '#F5E0DC' })
vim.api.nvim_set_hl(0, '@text.emphasis', { italic = true, fg = '#E8A2AF' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { fg = '#6E6C7E', strikethrough = true })
vim.api.nvim_set_hl(0, 'AerialStructIcon', { link = '@type' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { underline = true, sp = '#F28FAD' })
vim.api.nvim_set_hl(0, 'AerialNullIcon', { link = '@type' })
vim.api.nvim_set_hl(0, 'healthSuccess', { fg = '#B5E8E0' })
vim.api.nvim_set_hl(0, 'NotifyERRORBorder', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'NeoTreeTabSeparatorInactive', { bg = '#1E1E2E', fg = '#1E1E2E' })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'Character', { fg = '#B5E8E0' })
vim.api.nvim_set_hl(0, 'LspCodeLens', { fg = '#6E6C7E' })
vim.api.nvim_set_hl(0, 'NotifyWARNBorder', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#89DCEB' })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'AerialKeyIcon', { link = '@type' })
vim.api.nvim_set_hl(0, 'SpecialChar', { link = 'Special' })
vim.api.nvim_set_hl(0, '@property', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'NeoTreeDirectoryName', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { italic = true, fg = '#F5E0DC' })
vim.api.nvim_set_hl(0, 'NotifyTRACETitle', { fg = '#F5E0DC', italic = true })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = '#302D41', fg = '#C3BAC6' })
vim.api.nvim_set_hl(0, 'WinBar', { fg = '#F5E0DC' })
vim.api.nvim_set_hl(0, 'Todo', { fg = '#1E1E2E', bg = '#FAE3B0', bold = true })
vim.api.nvim_set_hl(0, 'Comment', { italic = true, fg = '#988BA2' })
vim.api.nvim_set_hl(0, 'MsgSeparator', {})
vim.api.nvim_set_hl(0, 'LspSignatureActiveParameter', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'Include', { fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, 'NeoTreeVertSplit', { bg = '#1E1E2E', fg = '#1E1E2E' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#302D41' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'TabLineSel', { bg = '#45475A', fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'IncSearch', { bg = '#F5C2E7', fg = '#1A1826' })
vim.api.nvim_set_hl(0, 'NotifyERRORIcon', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#45475A', fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'rainbowcol3', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'Repeat', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'AerialNumberIcon', { link = '@number' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#1A1826' })
vim.api.nvim_set_hl(0, 'AerialFieldIcon', { link = '@field' })
vim.api.nvim_set_hl(0, 'Define', { link = 'PreProc' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { underline = true, sp = '#F5E0DC' })
vim.api.nvim_set_hl(0, 'Search', { fg = '#F5C2E7', bg = '#575268', bold = true })
vim.api.nvim_set_hl(0, 'AerialNamespaceIcon', { link = '@namespace' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = '#1A1826', fg = '#45475A' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = '#45475A' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#F2CDCD' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'Structure', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = '#45475A' })
vim.api.nvim_set_hl(0, '@text.danger', { bg = '#F28FAD', fg = '#1E1E2E' })
vim.api.nvim_set_hl(0, 'SpellBad', { sp = '#F28FAD', undercurl = true })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { italic = true, fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { italic = true, fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'TabLine', { bg = '#45475A', fg = '#1A1826' })
vim.api.nvim_set_hl(0, 'Tag', { link = 'Special' })
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = '#374346' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { fg = '#D9E0EE', bold = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { underline = true, sp = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'AerialOperatorIcon', { link = '@operator' })
vim.api.nvim_set_hl(0, 'Title', { bold = true, fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'CmpItemKindFolder', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', { italic = true, fg = '#89DCEB' })
vim.api.nvim_set_hl(0, 'AerialEnumIcon', { link = '@type' })
vim.api.nvim_set_hl(0, 'StatusLine', { bg = '#1A1826', fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'MsgArea', { fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'NeoTreeRootName', { fg = '#96CDFB', bold = true })
vim.api.nvim_set_hl(0, 'Normal', { bg = '#1E1E2E', fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'NeoTreeExpander', { fg = '#6E6C7E' })
vim.api.nvim_set_hl(0, 'ModeMsg', { bold = true, fg = '#F2CDCD' })
vim.api.nvim_set_hl(0, 'Conditional', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { italic = true, fg = '#89DCEB' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { italic = true, fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'SpecialComment', { link = 'Special' })
vim.api.nvim_set_hl(0, '@function.macro', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, '@keyword.function', { fg = '#E8A2AF' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'DiffText', { bg = '#343e53' })
vim.api.nvim_set_hl(0, 'TabLineFill', {})
vim.api.nvim_set_hl(0, 'NeoTreeStatusLineNC', { bg = '#1A1826', fg = '#1A1826' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'NeoTreeFloatBorder', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#988BA2' })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = '#443245' })
vim.api.nvim_set_hl(0, '@number', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'AerialArrayIcon', { link = '@constant' })
vim.api.nvim_set_hl(0, 'Macro', { link = 'PreProc' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#96CDFB', italic = true, bold = true })
vim.api.nvim_set_hl(0, 'AerialConstructorIcon', { link = '@constructor' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { fg = '#F2CDCD' })
vim.api.nvim_set_hl(0, 'NeoTreeFileNameOpened', { fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { underline = true, sp = '#89DCEB' })
vim.api.nvim_set_hl(0, 'AerialLine', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'AerialPropertyIcon', { link = '@property' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { bold = true, bg = '#45475A' })
vim.api.nvim_set_hl(0, 'NotifyINFOBorder', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'NeoTreeFilterTerm', { fg = '#ABE9B3', bold = true })
vim.api.nvim_set_hl(0, 'lCursor', { bg = '#D9E0EE', fg = '#1E1E2E' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { fg = '#D9E0EE', bold = true })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = '#262a3c' })
vim.api.nvim_set_hl(0, 'qfFileName', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { italic = true, fg = '#F5E0DC' })
vim.api.nvim_set_hl(0, 'NotifyWARNTitle', { fg = '#FAE3B0', italic = true })
vim.api.nvim_set_hl(0, 'PreCondit', { link = 'PreProc' })
vim.api.nvim_set_hl(0, 'Cursor', { bg = '#D9E0EE', fg = '#1E1E2E' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'NotifyWARNIcon', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'MatchParen', { bold = true, bg = '#302D41' })
vim.api.nvim_set_hl(0, 'AerialFileIcon', { link = '@text.uri' })
vim.api.nvim_set_hl(0, 'NeoTreeGitUntracked', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, '@exception', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = '#E8A2AF' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'CurSearch', { bg = '#F28FAD', fg = '#1A1826' })
vim.api.nvim_set_hl(0, '@text.environment.name', { italic = true, fg = '#F2CDCD' })
vim.api.nvim_set_hl(0, '@namespace', { italic = true, fg = '#F5E0DC' })
vim.api.nvim_set_hl(0, '@text.warning', { bg = '#FAE3B0', fg = '#1E1E2E' })
vim.api.nvim_set_hl(0, 'VisualNOS', { bold = true, bg = '#45475A' })
vim.api.nvim_set_hl(0, 'NeoTreeGitUnstaged', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, '@variable', { fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, '@text.uri', { fg = '#F5E0DC', underline = true, italic = true })
vim.api.nvim_set_hl(0, '@text.underline', { underline = true })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#2a283a' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#45475A' })
vim.api.nvim_set_hl(0, '@text.title', { bold = true, fg = '#96CDFB' })
vim.api.nvim_set_hl(0, '@text.reference', { bold = true, fg = '#CDCFFF' })
vim.api.nvim_set_hl(0, '@text', { fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'Typedef', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, '@tag', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, '@text.strong', { bold = true, fg = '#E8A2AF' })
vim.api.nvim_set_hl(0, 'IndentBlanklineChar', { fg = '#302D41' })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { fg = '#DDB6F2' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, '@string', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, '@float', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, '@field.lua', { fg = '#CDCFFF' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#B5E8E0' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBorder', { fg = '#F5E0DC' })
vim.api.nvim_set_hl(0, 'NotifyINFOIcon', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'NeoTreeDimText', { fg = '#988BA2' })
vim.api.nvim_set_hl(0, 'AerialBooleanIcon', { link = '@boolean' })
vim.api.nvim_set_hl(0, 'AerialClassIcon', { link = '@type' })
vim.api.nvim_set_hl(0, 'CmpItemKindCopilot', { fg = '#B5E8E0' })
vim.api.nvim_set_hl(0, '@operator', { bold = true, fg = '#89DCEB' })
vim.api.nvim_set_hl(0, '@text.note', { bg = '#96CDFB', fg = '#1E1E2E' })
vim.api.nvim_set_hl(0, '@text.math', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, '@method', { italic = true, fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'SpellRare', { sp = '#ABE9B3', undercurl = true })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { fg = '#D9E0EE', bg = '#302D41', bold = true })
vim.api.nvim_set_hl(0, '@label', { fg = '#74C7EC' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, '@field', { fg = '#F5E0DC' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, '@constant.macro', { fg = '#DDB6F2' })
vim.api.nvim_set_hl(0, '@constant', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'TreesitterContextLineNumber', { fg = '#45475A' })
vim.api.nvim_set_hl(0, 'Conceal', { fg = '#988BA2' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, '@type.builtin', { italic = true, fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { fg = '#F2CDCD' })
vim.api.nvim_set_hl(0, 'rainbowcol7', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'rainbowcol6', { fg = '#F2CDCD' })
vim.api.nvim_set_hl(0, 'rainbowcol5', { fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, 'rainbowcol2', { fg = '#B5E8E0' })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'AerialConstantIcon', { link = '@constant' })
vim.api.nvim_set_hl(0, 'rainbowcol1', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'LeapLabelPrimary', { fg = '#1E1E2E', bg = '#c4f0ca', nocombine = true })
vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle', { fg = '#F8BD96', italic = true })
vim.api.nvim_set_hl(0, 'TreesitterContext', { fg = '#D9E0EE', bg = '#1A1826' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#C3BAC6' })
vim.api.nvim_set_hl(0, 'NeoTreeTabInactive', { fg = '#6E6C7E', bg = '#1E1E2E' })
vim.api.nvim_set_hl(0, 'NeoTreeTabActive', { bg = '#1A1826', fg = '#CDCFFF', bold = true })
vim.api.nvim_set_hl(0, 'NeoTreeFloatTitle', { fg = '#A6ADC8' })
vim.api.nvim_set_hl(0, 'NeoTreeGitStaged', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, '@variable.builtin', { italic = true, fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'AerialEventIcon', { link = '@type' })
vim.api.nvim_set_hl(0, 'NeoTreeGitModified', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'NeoTreeGitIgnored', { fg = '#6E6C7E' })
vim.api.nvim_set_hl(0, 'AerialTypeParameterIcon', { link = '@parameter' })
vim.api.nvim_set_hl(0, 'CmpItemKindEvent', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#6E6C7E' })
vim.api.nvim_set_hl(0, 'NeoTreeGitDeleted', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'Error', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'NeoTreeDirectoryIcon', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, 'LeapLabelSecondary', { fg = '#1E1E2E', bg = '#aee7f2', nocombine = true })
vim.api.nvim_set_hl(0, 'LeapMatch', { fg = '#c4f0ca', underline = true, nocombine = true })
vim.api.nvim_set_hl(0, 'Keyword', { italic = true, fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, 'AerialGuide', { fg = '#C3BAC6' })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'CmpItemKindColor', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'CmpItemKindFile', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'String', { fg = '#ABE9B3' })
vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = '#45475A' })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'healthWarning', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'healthError', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { fg = '#F28FAD' })
vim.api.nvim_set_hl(0, '@string.regex', { fg = '#F8BD96' })
vim.api.nvim_set_hl(0, 'WildMenu', { bg = '#6E6C7E' })
vim.api.nvim_set_hl(0, 'CmpItemMenu', { fg = '#D9E0EE' })
vim.api.nvim_set_hl(0, 'AerialInterfaceIcon', { link = '@type' })
vim.api.nvim_set_hl(0, 'AerialEnumMemberIcon', { link = '@field' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#F28FAD', italic = true, bold = true })
vim.api.nvim_set_hl(0, 'AerialVariableIcon', { link = '@constant' })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { italic = true, fg = '#F28FAD' })
vim.api.nvim_set_hl(0, 'qfLineNr', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = '#E8A2AF' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#96CDFB' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bold = true, bg = '#45475A' })
vim.api.nvim_set_hl(0, 'StorageClass', { fg = '#FAE3B0' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#DDB6F2' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextStart', { sp = '#D9E0EE', underline = true })
vim.api.nvim_set_hl(0, 'NeoTreeSymbolicLinkTarget', { fg = '#F5C2E7' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '#1A1826', fg = '#D9E0EE' })
