vim.g.colors_name = 'mariana'
vim.g.skip_ts_default_groups = true
vim.o.termguicolors = true

vim.api.nvim_set_hl(0, '@todo', { link = 'Todo' })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'Title', { bold = true, fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#f97b58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'Character', { fg = '#99c794', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Boolean', { italic = true, fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { link = 'LineNr' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'NotifyERRORBody', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DevIconMd', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBody', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@text.warning', { bold = true, fg = '#f9ae58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'SignColumn', { fg = '#d8dee9', bg = '#303841' })
vim.api.nvim_set_hl(0, '@string.regex', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bold = false, bg = '#46525c', fg = '#f7f7f7' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { undercurl = true, sp = '#f9ae58' })
vim.api.nvim_set_hl(0, 'Conceal', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#f9ae58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'markdownH1Delimiter', { bold = false, fg = '#f97b58', bg = '#2e363e' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { bg = '#2e363e', link = 'Delimiter' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextStart', { underdotted = true, sp = '#a6acb8' })
vim.api.nvim_set_hl(0, '@method.call', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DevIconGitConfig', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'NotifyERRORBorder', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#ec5f66', italic = true })
vim.api.nvim_set_hl(0, 'MatchParen', { bg = '#2f373f', bold = true })
vim.api.nvim_set_hl(0, 'String', { fg = '#99c794', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@constant.builtin', { italic = true, fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'helpSectionDelim', { bold = true, fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Struct', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Tag', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@function.builtin', { italic = true, fg = '#5c99d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Number', { fg = '#fac761', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Question', { link = 'MoreMsg' })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { fg = '#f97b58' })
vim.api.nvim_set_hl(0, 'DevIconTs', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'NotifyERRORIcon', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'SpellRare', { undercurl = true, sp = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'rainbowcol5', { fg = '#5fb4b4', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'helpHeader', { bold = true, fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DevIconDropbox', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, '@text.literal', { italic = true, fg = '#99c794', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'markdownCodeDelimiter', { fg = '#5c99d6', bg = '#2e363e' })
vim.api.nvim_set_hl(0, '@label', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'NotifyINFOIcon', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceCharBlankline', { link = 'NonText' })
vim.api.nvim_set_hl(0, '@variable', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'FoldColumn', { link = 'Comment' })
vim.api.nvim_set_hl(0, 'Define', { italic = true, fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { undercurl = true, sp = '#99c794' })
vim.api.nvim_set_hl(0, 'DevIconGitIgnore', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'WarningMsg', { link = 'ErrorMsg' })
vim.api.nvim_set_hl(0, 'packerHash', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'markdownLinkDelimiter', { fg = '#5fb4b4', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'NotifyWARNBorder', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@keyword.return', { bg = '#2f373f', link = '@keyword' })
vim.api.nvim_set_hl(0, 'helpHyperTextEntry', { link = '@text.uri' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon', { fg = '#f97b58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'SpecialComment', { underline = true, fg = '#788797', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@float', { link = 'Float' })
vim.api.nvim_set_hl(0, '@error', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'TelescopeTitle', { fg = '#d8dee9', bold = true })
vim.api.nvim_set_hl(0, '@function', { link = 'Function' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@text.title', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Macro', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#fac761', bold = true })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'DevIconGitModules', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle', { bold = true, fg = '#f97b58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Error', { fg = '#f97b58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@function.macro', { fg = '#5c99d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Todo', { bold = true, fg = '#5c99d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#46525c' })
vim.api.nvim_set_hl(0, '@string.escape', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, 'Delimiter', { fg = '#a6acb8', bg = '#2e363e' })
vim.api.nvim_set_hl(0, '@type.qualifier', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Include', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'packerStatusSuccess', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'markdownUrl', { underline = true, fg = '#5c99d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'StatusLine', { fg = '#d8dee9', bg = '#46525c' })
vim.api.nvim_set_hl(0, 'packerString', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'NotifyINFOBorder', { fg = '#99c794' })
vim.api.nvim_set_hl(0, ", 'TSInterface", { link = '@type' })
vim.api.nvim_set_hl(0, 'DevIconYaml', { link = 'DevIconToml' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#303841' })
vim.api.nvim_set_hl(0, 'Conditional', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@keyword.operator', { fg = '#f97b58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Structure', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@keyword', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'rainbowcol3', { fg = '#99c794', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#ec5f66', bold = true })
vim.api.nvim_set_hl(0, 'Function', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@method', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Substitute', { bg = '#46525c' })
vim.api.nvim_set_hl(0, '@text.uri', { bg = '#2f373f', fg = '#95b2d6', underdotted = true })
vim.api.nvim_set_hl(0, 'rainbowcol7', { fg = '#ee932b', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { strikethrough = true })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'DevIconGo', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'Repeat', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'DevIconTsx', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', { fg = '#99c794', bold = true })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { undercurl = true, sp = '#ec5f66' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#000000', bg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'Winseparator', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'helpHyperTextJump', { bg = '#2f373f', fg = '#5c99d6', underdotted = true })
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@string', { fg = '#99c794', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'rainbowcol4', { fg = '#ec5f66', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'TelescopePromptCounter', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'WildMenu', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'NotifyINFOTitle', { fg = '#99c794', bold = true })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'markdownCode', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBorder', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Float', { fg = '#fac761', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DevIconYml', { link = 'DevIconToml' })
vim.api.nvim_set_hl(0, 'Search', { fg = '#000000', bg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'NotifyWARNBody', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DevIconGitCommit', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'Comment', { fg = '#a6acb8', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@tag.attribute', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DiagnosticSignHint', { fg = '#5fb4b4', bold = true })
vim.api.nvim_set_hl(0, 'DevIconScheme', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = '#5fb4b4', bg = '#2e363e' })
vim.api.nvim_set_hl(0, '@text.emphasis', { italic = true })
vim.api.nvim_set_hl(0, 'qfFileName', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { fg = '#a6acb8', bg = 'NONE' })
vim.api.nvim_set_hl(0, 'helpExample', { fg = '#99c794', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'NotifyTRACETitle', { bold = true, fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Underlined', { underdotted = true })
vim.api.nvim_set_hl(0, 'NotifyINFOBody', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { bg = '#303841' })
vim.api.nvim_set_hl(0, '@character', { fg = '#99c794', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@text.danger', { bold = true, fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'Keyword', { italic = true, fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Exception', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'SpellCap', { undercurl = true, sp = '#f9ae58' })
vim.api.nvim_set_hl(0, 'DevIconDockerfile', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'DevIconGitAttributes', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'Folded', { fg = '#a6acb8', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Label', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBody', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'rainbowcol1', { fg = '#d8dee9', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { fg = '#d8dee9', bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'NotifyWARNTitle', { fg = '#f9ae58', bold = true })
vim.api.nvim_set_hl(0, 'DevIconJson', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'qfLineNr', { bold = true })
vim.api.nvim_set_hl(0, 'DiffText', { italic = true })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#d8dee9', bold = true })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#2e353e', fg = '#46525c' })
vim.api.nvim_set_hl(0, 'DevIconDsStore', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'Normal', { fg = '#d8dee9', bg = '#303841' })
vim.api.nvim_set_hl(0, 'markdownListMarker', { fg = '#fac761', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = '#46525c', bg = '#303841' })
vim.api.nvim_set_hl(0, '@operator', { link = 'Operator' })
vim.api.nvim_set_hl(0, '@parameter.reference', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@type.builtin', { italic = true, fg = '#5c99d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'SpecialChar', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { undercurl = true, sp = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@constant.macro', { link = 'Define' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#f7f7f7', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DiffAdd', { underline = true, sp = '#99c794' })
vim.api.nvim_set_hl(0, 'NotifyTRACEIcon', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@string.special', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { fg = '#f97b58' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#46525c' })
vim.api.nvim_set_hl(0, '@property', { fg = '#95b2d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@number', { link = 'Number' })
vim.api.nvim_set_hl(0, '@character.special', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, 'PreCondit', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'SpellBad', { undercurl = true, sp = '#ec5f66' })
vim.api.nvim_set_hl(0, '@text', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@tag', { link = 'Tag' })
vim.api.nvim_set_hl(0, '@text.note', { bold = true, fg = '#99c794', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'TabLineFill', { fg = '#a6acb8', bg = '#46525c' })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, '@type', { link = 'Type' })
vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', { fg = '#f9ae58', bold = true })
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#a6acb8', bg = '#46525c' })
vim.api.nvim_set_hl(0, '@text.strong', { bold = true })
vim.api.nvim_set_hl(0, '@include', { fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'StorageClass', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DiagnosticSignError', { fg = '#ec5f66', bold = true })
vim.api.nvim_set_hl(0, '@constant', { link = 'Constant' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { fg = '#95b2d6' })
vim.api.nvim_set_hl(0, '@function.call', { fg = '#5c99d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'LineNr', { bg = '#46525c', fg = '#f7f7f7' })
vim.api.nvim_set_hl(0, 'SpellLocal', { undercurl = true, sp = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@namespace', { fg = '#f9ae58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@keyword.function', { italic = true, fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, '@text.underline', { underline = true })
vim.api.nvim_set_hl(0, 'Typedef', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@field', { fg = '#95b2d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'markdownH2Delimiter', { bold = false, fg = '#f97b58', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'markdownRule', { fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#ffffff', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'helpCommand', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'rainbowcol2', { fg = '#cc8ec6', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceChar', { link = 'NonText' })
vim.api.nvim_set_hl(0, 'rainbowcol6', { fg = '#fac761', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'helpURL', { underline = true, fg = '#5c99d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'NotifyWARNIcon', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, '@symbol', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@boolean', { link = 'Boolean' })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#99c794', bold = true })
vim.api.nvim_set_hl(0, 'DiffChange', { underline = true, sp = '#ec5f66' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#5fb4b4', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBorder', { fg = '#f97b58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'markdownLinkText', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@comment', { fg = '#a6acb8', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'TabLineSel', { fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@text.reference', { fg = '#d8dee9', underdotted = false })
vim.api.nvim_set_hl(0, 'NotifyERRORTitle', { fg = '#ec5f66', bold = true })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'DevIconToml', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { fg = '#cc8ec6' })
