vim.g.colors_name = 'mariana'

vim.api.nvim_set_hl(0, 'Conditional', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#cc8ec6', italic = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@number', { link = 'Number' })
vim.api.nvim_set_hl(0, 'SpellRare', { sp = '#cc8ec6', undercurl = true })
vim.api.nvim_set_hl(0, 'DevIconDsStore', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { sp = '#f9ae58', undercurl = true })
vim.api.nvim_set_hl(0, 'DiffAdd', { sp = '#99c794', underline = true })
vim.api.nvim_set_hl(0, 'DevIconScheme', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'LineNrAbove', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, '@operator', { link = 'Operator' })
vim.api.nvim_set_hl(0, 'markdownLinkText', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'Number', { bg = '#2f373f', fg = '#fac761' })
vim.api.nvim_set_hl(0, '@function.macro', { bg = '#2f373f', fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'NotifyERRORBorder', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'Operator', { bg = '#2f373f', fg = '#f97b58' })
vim.api.nvim_set_hl(0, '@property', { bg = '#2f373f', fg = '#95b2d6' })
vim.api.nvim_set_hl(0, 'WarningMsg', { link = 'ErrorMsg' })
vim.api.nvim_set_hl(0, 'Exception', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, '@keyword', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'Search', { bg = '#f9ae58', fg = '#000000' })
vim.api.nvim_set_hl(0, 'ModeMsg', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { fg = '#46525c', bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'helpSectionDelim', { bold = true, fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DevIconYaml', { link = 'DevIconToml' })
vim.api.nvim_set_hl(0, 'Float', { bg = '#2f373f', fg = '#fac761' })
vim.api.nvim_set_hl(0, 'Substitute', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'PreProc', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'Delimiter', { bg = '#2e363e', fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, '@parameter.reference', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'Define', { fg = '#cc8ec6', italic = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Structure', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'Character', { bg = '#2f373f', fg = '#99c794' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBody', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@text.danger', { bold = true, fg = '#ec5f66', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#303841' })
vim.api.nvim_set_hl(0, 'TelescopeMatching', { bg = '#303841' })
vim.api.nvim_set_hl(0, '@punctuation.special', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@character', { bg = '#2f373f', fg = '#99c794' })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'NotifyINFOBorder', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'NotifyERRORBody', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'IncSearch', { bg = '#f9ae58', fg = '#000000' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextStart', { sp = '#a6acb8', underdotted = true })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'Title', { bold = true, fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = '#46525c' })
vim.api.nvim_set_hl(0, '@method.call', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@type.qualifier', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@text.warning', { bold = true, fg = '#f9ae58', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Type', { bg = '#2f373f', fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'NotifyWARNIcon', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'DevIconDockerfile', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'DevIconGo', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'Statement', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@float', { link = 'Float' })
vim.api.nvim_set_hl(0, '@text.title', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'DevIconGitConfig', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@text.strong', { bold = true })
vim.api.nvim_set_hl(0, 'markdownCode', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'Question', { link = 'MoreMsg' })
vim.api.nvim_set_hl(0, 'DevIconJson', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, '@keyword.return', { bg = '#2f373f', link = '@keyword' })
vim.api.nvim_set_hl(0, 'rainbowcol7', { bg = '#2e363e', fg = '#ee932b' })
vim.api.nvim_set_hl(0, 'rainbowcol1', { bg = '#2e363e', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@error', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@keyword.operator', { bg = '#2f373f', fg = '#f97b58' })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'Todo', { bold = true, fg = '#5c99d6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@type', { link = 'Type' })
vim.api.nvim_set_hl(0, 'DevIconGitModules', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'NotifyWARNBody', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'MoreMsg', { bold = true, fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@parameter', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'Comment', { bg = '#2f373f', fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'DevIconTs', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { link = 'LineNr' })
vim.api.nvim_set_hl(0, 'DiagnosticSignWarn', { bold = true, fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'NotifyWARNBorder', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBody', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'DevIconGitCommit', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'FoldColumn', { link = 'Comment' })
vim.api.nvim_set_hl(0, 'Include', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'Constant', { bg = '#2f373f', fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'Typedef', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'TelescopePromptCounter', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@function.builtin', { fg = '#5c99d6', italic = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@comment', { bg = '#2f373f', fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'markdownUrl', { fg = '#5c99d6', underline = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { bold = true, fg = '#fac761' })
vim.api.nvim_set_hl(0, 'DevIconTsx', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'MatchParen', { bold = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#303841', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@text.reference', { underdotted = false, fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'LineNrBelow', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { fg = '#95b2d6' })
vim.api.nvim_set_hl(0, 'DevIconGitAttributes', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'TelescopeSelectionCaret', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@constant.macro', { link = 'Define' })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = '#2e353e', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'DiagnosticSignHint', { bold = true, fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'rainbowcol6', { bg = '#2e363e', fg = '#fac761' })
vim.api.nvim_set_hl(0, 'SpecialComment', { fg = '#788797', underline = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, '@include', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceChar', { link = 'NonText' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'helpExample', { bg = '#2f373f', fg = '#99c794' })
vim.api.nvim_set_hl(0, 'DevIconMd', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, '@method', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { bg = '#2f373f', fg = '#f7f7f7' })
vim.api.nvim_set_hl(0, 'Tag', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bold = false, bg = '#46525c', fg = '#f7f7f7' })
vim.api.nvim_set_hl(0, 'SpellBad', { sp = '#ec5f66', undercurl = true })
vim.api.nvim_set_hl(0, '@text.uri', { fg = '#95b2d6', bg = '#2f373f', underdotted = true })
vim.api.nvim_set_hl(0, 'Boolean', { fg = '#ec5f66', italic = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@namespace', { bg = '#2f373f', fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'markdownH2Delimiter', { bold = false, fg = '#f97b58', bg = '#2e363e' })
vim.api.nvim_set_hl(0, '@keyword.function', { fg = '#cc8ec6', italic = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { bg = 'NONE', fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'SpellCap', { sp = '#f9ae58', undercurl = true })
vim.api.nvim_set_hl(0, 'rainbowcol5', { bg = '#2e363e', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'Label', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'NotifyERRORTitle', { bold = true, fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'SpecialChar', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'markdownRule', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'DiffDelete', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, '@string.special', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, 'NotifyINFOIcon', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'NotifyWARNTitle', { bold = true, fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, '@todo', { link = 'Todo' })
vim.api.nvim_set_hl(0, 'DiffText', { italic = true })
vim.api.nvim_set_hl(0, '@character.special', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, 'markdownLinkDelimiter', { bg = '#2e363e', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'NotifyTRACEIcon', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'TelescopeTitle', { bold = true, fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@text.emphasis', { italic = true })
vim.api.nvim_set_hl(0, '@tag', { link = 'Tag' })
vim.api.nvim_set_hl(0, 'Winseparator', { fg = '#46525c' })
vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'Conceal', { fg = '#a6acb8' })
vim.api.nvim_set_hl(0, '@text.note', { bold = true, fg = '#99c794', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'helpURL', { fg = '#5c99d6', underline = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@label', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, '@string.escape', { link = 'SpecialChar' })
vim.api.nvim_set_hl(0, 'DevIconGitIgnore', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'Macro', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'SpecialKey', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'DiagnosticSignInfo', { bold = true, fg = '#99c794' })
vim.api.nvim_set_hl(0, 'NotifyERRORIcon', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, '@tag.attribute', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'TelescopeSelection', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'StatusLine', { bg = '#46525c', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'helpHeader', { bold = true, fg = '#d8dee9', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'packerHash', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'Error', { bg = '#2f373f', fg = '#f97b58' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { bold = true, fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { sp = '#99c794', undercurl = true })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { strikethrough = true })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBorder', { bg = '#2f373f', fg = '#f97b58' })
vim.api.nvim_set_hl(0, 'rainbowcol3', { bg = '#2e363e', fg = '#99c794' })
vim.api.nvim_set_hl(0, '@symbol', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#f7f7f7', bg = '#46525c' })
vim.api.nvim_set_hl(0, 'qfFileName', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'PreCondit', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'String', { bg = '#2f373f', fg = '#99c794' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#46525c' })
vim.api.nvim_set_hl(0, '@function.call', { bg = '#2f373f', fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { fg = '#ec5f66' })
vim.api.nvim_set_hl(0, '@constant', { link = 'Constant' })
vim.api.nvim_set_hl(0, '@constant.builtin', { fg = '#ec5f66', italic = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, '@variable.builtin', { italic = true, fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'DiffChange', { sp = '#ec5f66', underline = true })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#2f373f', fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'Normal', { bg = '#303841', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#46525c', fg = '#a6acb8' })
vim.api.nvim_set_hl(0, '@field', { bg = '#2f373f', fg = '#95b2d6' })
vim.api.nvim_set_hl(0, 'markdownListMarker', { bg = '#2f373f', fg = '#fac761' })
vim.api.nvim_set_hl(0, '@string', { bg = '#2f373f', fg = '#99c794' })
vim.api.nvim_set_hl(0, 'packerString', { fg = '#99c794' })
vim.api.nvim_set_hl(0, 'TabLineSel', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, '@type.builtin', { fg = '#5c99d6', italic = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { fg = '#f97b58' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { sp = '#ec5f66', undercurl = true })
vim.api.nvim_set_hl(0, 'Special', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'NotifyTRACETitle', { bold = true, fg = '#cc8ec6', bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'Function', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'Struct', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { bg = '#2e363e', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'NotifyINFOTitle', { bold = true, fg = '#99c794' })
vim.api.nvim_set_hl(0, 'Identifier', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { sp = '#5fb4b4', undercurl = true })
vim.api.nvim_set_hl(0, 'StorageClass', { bg = '#2f373f', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, 'Underlined', { underdotted = true })
vim.api.nvim_set_hl(0, 'markdownH1Delimiter', { bold = false, fg = '#f97b58', bg = '#2e363e' })
vim.api.nvim_set_hl(0, 'markdownCodeDelimiter', { bg = '#2e363e', fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'DevIconYml', { link = 'DevIconToml' })
vim.api.nvim_set_hl(0, '@text.literal', { fg = '#99c794', italic = true, bg = '#2f373f' })
vim.api.nvim_set_hl(0, 'qfLineNr', { bold = true })
vim.api.nvim_set_hl(0, 'NotifyINFOBody', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'SpellLocal', { sp = '#5fb4b4', undercurl = true })
vim.api.nvim_set_hl(0, 'helpCommand', { bg = '#46525c' })
vim.api.nvim_set_hl(0, 'rainbowcol2', { bg = '#2e363e', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { fg = '#ffffff' })
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceCharBlankline', { link = 'NonText' })
vim.api.nvim_set_hl(0, 'DevIconDropbox', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'TabLine', { bg = '#46525c', fg = '#a6acb8' })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { fg = '#f97b58' })
vim.api.nvim_set_hl(0, '@text', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { bold = true, fg = '#99c794' })
vim.api.nvim_set_hl(0, 'Repeat', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBorder', { bg = '#2f373f', fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'helpHyperTextJump', { fg = '#5c99d6', bg = '#2f373f', underdotted = true })
vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon', { bg = '#2f373f', fg = '#f97b58' })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { fg = '#cc8ec6' })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { fg = '#f9ae58' })
vim.api.nvim_set_hl(0, 'rainbowcol4', { bg = '#2e363e', fg = '#ec5f66' })
vim.api.nvim_set_hl(0, '@variable', { bg = '#2f373f', fg = '#d8dee9' })
vim.api.nvim_set_hl(0, 'FloatBorder', { bg = '#303841', fg = '#46525c' })
vim.api.nvim_set_hl(0, 'DiagnosticSignError', { bold = true, fg = '#ec5f66' })
vim.api.nvim_set_hl(0, '@boolean', { link = 'Boolean' })
vim.api.nvim_set_hl(0, 'packerStatusSuccess', { fg = '#99c794' })
vim.api.nvim_set_hl(0, '@string.regex', { bg = '#2f373f', fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#46525c' })
vim.api.nvim_set_hl(0, '@function', { link = 'Function' })
vim.api.nvim_set_hl(0, '@text.underline', { underline = true })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { fg = '#5c99d6' })
vim.api.nvim_set_hl(0, 'WildMenu', { bg = '#2e353e' })
vim.api.nvim_set_hl(0, 'helpHyperTextEntry', { link = '@text.uri' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { bg = '#2e363e', link = 'Delimiter' })
vim.api.nvim_set_hl(0, 'DevIconToml', { fg = '#5fb4b4' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle', { bold = true, fg = '#f97b58', bg = '#2f373f' })
