vim.g.colors_name = 'tokyonight'

vim.g.terminal_color_11 = "#e0af68"
vim.g.terminal_color_5 = "#bb9af7"
vim.g.terminal_color_6 = "#7dcfff"
vim.g.terminal_color_10 = "#9ece6a"
vim.g.terminal_color_8 = "#414868"
vim.g.terminal_color_13 = "#bb9af7"
vim.g.terminal_color_9 = "#f7768e"
vim.g.terminal_color_12 = "#7aa2f7"
vim.g.terminal_color_4 = "#7aa2f7"
vim.g.terminal_color_1 = "#f7768e"
vim.g.terminal_color_0 = "#15161e"
vim.g.terminal_color_14 = "#7dcfff"
vim.g.terminal_color_7 = "#a9b1d6"
vim.g.terminal_color_3 = "#e0af68"
vim.g.terminal_color_2 = "#9ece6a"
vim.g.terminal_color_15 = "#c0caf5"

vim.api.nvim_set_hl(0, "VisualNOS", { bg = "#2b3e71" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#7dcfff", italic = true })
vim.api.nvim_set_hl(0, "DiffDelete", { bg = "#210b0b" })
vim.api.nvim_set_hl(0, "PmenuSbar", { bg = "#222229" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#3b4261", bg = "#16161e" })
vim.api.nvim_set_hl(0, "CmpItemKindUnit", { fg = "#ff9e64", bg = "NONE" })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = "#db4b4b" })
vim.api.nvim_set_hl(0, "NotifyTRACEIcon", { fg = "#9d7cd8" })
vim.api.nvim_set_hl(0, "NotifyINFOBody", { fg = "#c0caf5", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "CmpItemKindModule", { fg = "#e0af68", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", { fg = "#7aa2f7", bg = "NONE" })
vim.api.nvim_set_hl(0, "LeapMatch", { bg = "#ff007c", fg = "#c0caf5", bold = true })
vim.api.nvim_set_hl(0, "NotifyDEBUGIcon", { fg = "#565f89" })
vim.api.nvim_set_hl(0, "Function", { fg = "#7aa2f7", italic = true })
vim.api.nvim_set_hl(0, "NotifyWARNBody", { fg = "#c0caf5", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "Todo", { bg = "#e0af68", fg = "#1a1b26" })
vim.api.nvim_set_hl(0, "@parameter", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "NormalFloat", { fg = "#c0caf5", bg = "#16161e" })
vim.api.nvim_set_hl(0, "DiffAdd", { bg = "#0a191b" })
vim.api.nvim_set_hl(0, "NotifyERRORBorder", { fg = "#421717", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#565f89", italic = true })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#536c9e" })
vim.api.nvim_set_hl(0, "Cursor", { fg = "#1a1b26", bg = "#c0caf5" })
vim.api.nvim_set_hl(0, "Conceal", { fg = "#737aa2" })
vim.api.nvim_set_hl(0, "NotifyWARNBorder", { fg = "#43351f", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "@text.reference", { fg = "#1abc9c" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextInfo", { bg = "#011316", fg = "#0db9d7" })
vim.api.nvim_set_hl(0, "CmpItemKindConstant", { fg = "#bb9af7", bg = "NONE" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#bb9af7" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#7dcfff" })
vim.api.nvim_set_hl(0, "CmpItemKindMethod", { fg = "#7aa2f7", bg = "NONE" })
vim.api.nvim_set_hl(0, "NeoTreeNormalNC", { fg = "#a9b1d6", bg = "#16161e" })
vim.api.nvim_set_hl(0, "qfFileName", { fg = "#7aa2f7" })
vim.api.nvim_set_hl(0, "LspReferenceRead", { bg = "#3b4261" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#1abc9c" })
vim.api.nvim_set_hl(0, "@text.danger", { fg = "#1a1b26", bg = "#db4b4b" })
vim.api.nvim_set_hl(0, "Folded", { fg = "#7aa2f7", bg = "#3b4261" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#0db9d7" })
vim.api.nvim_set_hl(0, "LspSignatureActiveParameter", { fg = "#ff9e64" })
vim.api.nvim_set_hl(0, "Character", { fg = "#9ece6a" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#266d6a" })
vim.api.nvim_set_hl(0, "NormalNC", { fg = "#c0caf5", bg = "#16161e" })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#15161e" })
vim.api.nvim_set_hl(0, "Question", { fg = "#7aa2f7" })
vim.api.nvim_set_hl(0, "@text.title", { bold = true })
vim.api.nvim_set_hl(0, "CmpItemKindVariable", { fg = "#bb9af7", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiffChange", { bg = "#090b11" })
vim.api.nvim_set_hl(0, "@text.environment.name", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "Whitespace", { fg = "#3b4261" })
vim.api.nvim_set_hl(0, "rainbowcol5", { fg = "#7aa2f7" })
vim.api.nvim_set_hl(0, "CmpItemKindOperator", { fg = "#73daca", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpellLocal", { undercurl = true, sp = "#0db9d7" })
vim.api.nvim_set_hl(0, "Title", { fg = "#7aa2f7", bold = true })
vim.api.nvim_set_hl(0, "PmenuSel", { bg = "#2f354e" })
vim.api.nvim_set_hl(0, "TabLineFill", { bg = "#15161e" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#3b4261" })
vim.api.nvim_set_hl(0, "FoldColumn", { bg = "#1a1b26", fg = "#565f89" })
vim.api.nvim_set_hl(0, "@punctuation.special.markdown", { fg = "#ff9e64", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { sp = "#e0af68", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#db4b4b" })
vim.api.nvim_set_hl(0, "CursorColumn", { bg = "#292e42" })
vim.api.nvim_set_hl(0, "@parameter.latex", { fg = "#41a6b5" })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#bb9af7", italic = true })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#bb9af7", italic = true })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { bg = "#3b4261" })
vim.api.nvim_set_hl(0, "CmpItemKindFunction", { fg = "#7aa2f7", bg = "NONE" })
vim.api.nvim_set_hl(0, "MsgArea", { fg = "#a9b1d6" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { sp = "#db4b4b", undercurl = true })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#7aa2f7" })
vim.api.nvim_set_hl(0, "LeapBackdrop", { fg = "#545c7e" })
vim.api.nvim_set_hl(0, "WildMenu", { bg = "#2b3e71" })
vim.api.nvim_set_hl(0, "@function.latex", { fg = "#bb9af7" })
vim.api.nvim_set_hl(0, "NotifyINFOIcon", { fg = "#0db9d7" })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "#f7768e" })
vim.api.nvim_set_hl(0, "QuickFixLine", { bg = "#2b3e71", bold = true })
vim.api.nvim_set_hl(0, "@text.warning", { fg = "#1a1b26", bg = "#e0af68" })
vim.api.nvim_set_hl(0, "@variable", { italic = true })
vim.api.nvim_set_hl(0, "CmpItemKindReference", { fg = "#bb9af7", bg = "NONE" })
vim.api.nvim_set_hl(0, "NotifyDEBUGBorder", { fg = "#1a1d29", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "@text.environment", { fg = "#0db9d7" })
vim.api.nvim_set_hl(0, "@text.math", { fg = "#2ac3de" })
vim.api.nvim_set_hl(0, "@string.escape", { fg = "#bb9af7" })
vim.api.nvim_set_hl(0, "NotifyINFOTitle", { fg = "#0db9d7" })
vim.api.nvim_set_hl(0, "LspReferenceText", { bg = "#3b4261" })
vim.api.nvim_set_hl(0, "@string.regex", { fg = "#b4f9f8" })
vim.api.nvim_set_hl(0, "NotifyERRORBody", { fg = "#c0caf5", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = "#a9b1d6" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "@property", { fg = "#73daca" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { fg = "#2ac3de", bg = "NONE" })
vim.api.nvim_set_hl(0, "@preproc", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "Substitute", { bg = "#f7768e", fg = "#15161e" })
vim.api.nvim_set_hl(0, "@label", { fg = "#7aa2f7" })
vim.api.nvim_set_hl(0, "Pmenu", { bg = "#16161e", fg = "#c0caf5" })
vim.api.nvim_set_hl(0, "CmpItemKindClass", { fg = "#ff9e64", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextError", { bg = "#160808", fg = "#db4b4b" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#737aa2" })
vim.api.nvim_set_hl(0, "@constructor", { fg = "#bb9af7" })
vim.api.nvim_set_hl(0, "NotifyTRACEBody", { fg = "#c0caf5", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "Directory", { fg = "#7aa2f7" })
vim.api.nvim_set_hl(0, "NotifyDEBUGBody", { fg = "#c0caf5", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "NotifyTRACETitle", { fg = "#9d7cd8" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = "#1a1b26" })
vim.api.nvim_set_hl(0, "NotifyDEBUGTitle", { fg = "#565f89" })
vim.api.nvim_set_hl(0, "CmpItemKindField", { fg = "#73daca", bg = "NONE" })
vim.api.nvim_set_hl(0, "NotifyERRORTitle", { fg = "#db4b4b" })
vim.api.nvim_set_hl(0, "NotifyWARNIcon", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "NotifyERRORIcon", { fg = "#db4b4b" })
vim.api.nvim_set_hl(0, "SignColumnSB", { bg = "#16161e", fg = "#3b4261" })
vim.api.nvim_set_hl(0, "Underlined", { underline = true })
vim.api.nvim_set_hl(0, "Normal", { fg = "#c0caf5", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#292e42" })
vim.api.nvim_set_hl(0, "ColorColumn", { bg = "#15161e" })
vim.api.nvim_set_hl(0, "NotifyINFOBorder", { fg = "#043841", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "healthWarning", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "IndentBlanklineContextChar", { fg = "#9d7cd8", nocombine = true })
vim.api.nvim_set_hl(0, "IndentBlanklineChar", { fg = "#3b4261", nocombine = true })
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", { fg = "#737aa2", bg = "NONE" })
vim.api.nvim_set_hl(0, "IncSearch", { bg = "#ff9e64", fg = "#15161e" })
vim.api.nvim_set_hl(0, "CursorIM", { fg = "#1a1b26", bg = "#c0caf5" })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = "#a9b1d6", bold = true })
vim.api.nvim_set_hl(0, "WarningMsg", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", { fg = "#73daca", bg = "NONE" })
vim.api.nvim_set_hl(0, "String", { fg = "#9ece6a" })
vim.api.nvim_set_hl(0, "NotifyWARNTitle", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "Search", { bg = "#3d59a1", fg = "#c0caf5" })
vim.api.nvim_set_hl(0, "CmpItemKindProperty", { fg = "#73daca", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindEnum", { fg = "#ff9e64", bg = "NONE" })
vim.api.nvim_set_hl(0, "LeapLabelSecondary", { fg = "#73daca", bold = true })
vim.api.nvim_set_hl(0, "CmpItemKindStruct", { fg = "#ff9e64", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindInterface", { fg = "#ff9e64", bg = "NONE" })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#9d7cd8", italic = true })
vim.api.nvim_set_hl(0, "Constant", { fg = "#ff9e64" })
vim.api.nvim_set_hl(0, "SpellCap", { undercurl = true, sp = "#e0af68" })
vim.api.nvim_set_hl(0, "NeoTreeNormal", { fg = "#a9b1d6", bg = "#16161e" })
vim.api.nvim_set_hl(0, "CmpItemKindValue", { fg = "#bb9af7", bg = "NONE" })
vim.api.nvim_set_hl(0, "rainbowcol1", { fg = "#f7768e" })
vim.api.nvim_set_hl(0, "@text.note", { fg = "#1a1b26", bg = "#0db9d7" })
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", { fg = "#7dcfff", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpellBad", { undercurl = true, sp = "#db4b4b" })
vim.api.nvim_set_hl(0, "Visual", { bg = "#2b3e71" })
vim.api.nvim_set_hl(0, "CmpItemKindDefault", { fg = "#a9b1d6", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { fg = "#2ac3de", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", { fg = "#3b4261", strikethrough = true, bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemAbbr", { fg = "#c0caf5", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindEvent", { fg = "#ff9e64", bg = "NONE" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#15161e", bg = "#7aa2f7" })
vim.api.nvim_set_hl(0, "rainbowcol6", { fg = "#bb9af7" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#a9b1d6", bg = "#16161e" })
vim.api.nvim_set_hl(0, "Error", { fg = "#db4b4b" })
vim.api.nvim_set_hl(0, "TelescopeNormal", { fg = "#c0caf5", bg = "#16161e" })
vim.api.nvim_set_hl(0, "qfLineNr", { fg = "#737aa2" })
vim.api.nvim_set_hl(0, "WinSeparator", { fg = "#15161e", bold = true })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#b2555b" })
vim.api.nvim_set_hl(0, "LspInfoBorder", { fg = "#3d59a1", bg = "#16161e" })
vim.api.nvim_set_hl(0, "rainbowcol7", { fg = "#9d7cd8" })
vim.api.nvim_set_hl(0, "healthSuccess", { fg = "#73daca" })
vim.api.nvim_set_hl(0, "SignColumn", { bg = "#1a1b26", fg = "#3b4261" })
vim.api.nvim_set_hl(0, "rainbowcol3", { fg = "#9ece6a" })
vim.api.nvim_set_hl(0, "rainbowcol4", { fg = "#1abc9c" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#89ddff" })
vim.api.nvim_set_hl(0, "rainbowcol2", { fg = "#e0af68" })
vim.api.nvim_set_hl(0, "LspCodeLens", { fg = "#565f89" })
vim.api.nvim_set_hl(0, "@text.literal.markdown_inline", { bg = "#414868", fg = "#7aa2f7" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextWarn", { bg = "#16120a", fg = "#e0af68" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#545c7e" })
vim.api.nvim_set_hl(0, "DiagnosticVirtualTextHint", { bg = "#031310", fg = "#1abc9c" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { sp = "#0db9d7", undercurl = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { sp = "#1abc9c", undercurl = true })
vim.api.nvim_set_hl(0, "@field", { fg = "#73daca" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#545c7e" })
vim.api.nvim_set_hl(0, "TelescopeBorder", { fg = "#3d59a1", bg = "#16161e" })
vim.api.nvim_set_hl(0, "NotifyTRACEBorder", { fg = "#2f2541", bg = "#1a1b26" })
vim.api.nvim_set_hl(0, "DiffText", { bg = "#394b70" })
vim.api.nvim_set_hl(0, "Special", { fg = "#2ac3de" })
vim.api.nvim_set_hl(0, "lCursor", { fg = "#1a1b26", bg = "#c0caf5" })
vim.api.nvim_set_hl(0, "Type", { fg = "#2ac3de" })
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", { fg = "#73daca", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemMenu", { fg = "#565f89", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpellRare", { undercurl = true, sp = "#1abc9c" })
vim.api.nvim_set_hl(0, "LeapLabelPrimary", { fg = "#ff007c", bold = true })
vim.api.nvim_set_hl(0, "TabLine", { bg = "#16161e", fg = "#3b4261" })
vim.api.nvim_set_hl(0, "healthError", { fg = "#db4b4b" })
vim.api.nvim_set_hl(0, "CurSearch", { link = "IncSearch" })
vim.api.nvim_set_hl(0, "PmenuThumb", { bg = "#3b4261" })
vim.api.nvim_set_hl(0, "FloatBorder", { fg = "#3d59a1", bg = "#16161e" })
vim.api.nvim_set_hl(0, "MatchParen", { bg = "#414868", bold = true })