vim.g.colors_name = 'tokyonight'
vim.g.skip_ts_default_groups = true
vim.o.termguicolors = true

vim.g.terminal_color_6 = '#7dcfff'
vim.g.terminal_color_0 = '#15161e'
vim.g.terminal_color_10 = '#9ece6a'
vim.g.terminal_color_1 = '#f7768e'
vim.g.terminal_color_12 = '#7aa2f7'
vim.g.terminal_color_2 = '#9ece6a'
vim.g.terminal_color_14 = '#7dcfff'
vim.g.terminal_color_15 = '#c0caf5'
vim.g.terminal_color_11 = '#e0af68'
vim.g.terminal_color_5 = '#bb9af7'
vim.g.terminal_color_8 = '#414868'
vim.g.terminal_color_13 = '#bb9af7'
vim.g.terminal_color_4 = '#7aa2f7'
vim.g.terminal_color_3 = '#e0af68'
vim.g.terminal_color_9 = '#f7768e'
vim.g.terminal_color_7 = '#a9b1d6'

vim.api.nvim_set_hl(0, 'Substitute', { fg = '#15161e', bg = '#f7768e' })
vim.api.nvim_set_hl(0, 'VertSplit', { fg = '#15161e' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = '#1abc9c' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBody', { bg = '#1a1b26', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'SpellLocal', { undercurl = true, sp = '#0db9d7' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', { fg = '#0db9d7', bg = '#011316' })
vim.api.nvim_set_hl(0, 'rainbowcol1', { fg = '#f7768e' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = '#737aa2' })
vim.api.nvim_set_hl(0, 'String', { fg = '#9ece6a' })
vim.api.nvim_set_hl(0, 'SpecialKey', { fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'qfFileName', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, '@text.literal.markdown_inline', { fg = '#7aa2f7', bg = '#414868' })
vim.api.nvim_set_hl(0, 'NotifyTRACEIcon', { fg = '#9d7cd8' })
vim.api.nvim_set_hl(0, 'SpellBad', { undercurl = true, sp = '#db4b4b' })
vim.api.nvim_set_hl(0, 'CursorIM', { bg = '#c0caf5', fg = '#1a1b26' })
vim.api.nvim_set_hl(0, 'NotifyTRACETitle', { fg = '#9d7cd8' })
vim.api.nvim_set_hl(0, '@text.math', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { bg = 'NONE', fg = '#7dcfff' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGBorder', { bg = '#1a1b26', fg = '#1a1d29' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { fg = '#1abc9c', bg = '#031310' })
vim.api.nvim_set_hl(0, 'NotifyWARNTitle', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGTitle', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'Identifier', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { bg = 'NONE', fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'PreProc', { fg = '#7dcfff' })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = '#1a1b26' })
vim.api.nvim_set_hl(0, 'Normal', { bg = '#1a1b26', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NormalNC', { bg = '#1a1b26', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = '#090b11' })
vim.api.nvim_set_hl(0, 'Function', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'Character', { fg = '#9ece6a' })
vim.api.nvim_set_hl(0, 'rainbowcol7', { fg = '#9d7cd8' })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { bg = 'NONE', fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'MatchParen', { bold = true, fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#292e42' })
vim.api.nvim_set_hl(0, 'MsgArea', { fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'NotifyINFOTitle', { fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'NotifyERRORIcon', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'CmpDocumentationBorder', { bg = '#16161e', fg = '#3d59a1' })
vim.api.nvim_set_hl(0, 'SpellCap', { undercurl = true, sp = '#e0af68' })
vim.api.nvim_set_hl(0, 'Conceal', { fg = '#737aa2' })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#3b4261', fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#222229' })
vim.api.nvim_set_hl(0, 'rainbowcol2', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { strikethrough = true, fg = '#3b4261', bg = 'NONE' })
vim.api.nvim_set_hl(0, 'Error', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'Cursor', { bg = '#c0caf5', fg = '#1a1b26' })
vim.api.nvim_set_hl(0, 'CmpItemMenu', { bg = 'NONE', fg = '#565f89' })
vim.api.nvim_set_hl(0, 'Comment', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#2f354e' })
vim.api.nvim_set_hl(0, 'LeapBackdrop', { fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'DiffText', { bg = '#394b70' })
vim.api.nvim_set_hl(0, 'rainbowcol3', { fg = '#9ece6a' })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { bg = 'NONE', fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'Question', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = '#16161e', fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = '#0a191b' })
vim.api.nvim_set_hl(0, 'Constant', { fg = '#ff9e64' })
vim.api.nvim_set_hl(0, '@variable.builtin', { fg = '#f7768e' })
vim.api.nvim_set_hl(0, '@variable', { italic = true })
vim.api.nvim_set_hl(0, '@text.danger', { bg = '#db4b4b', fg = '#1a1b26' })
vim.api.nvim_set_hl(0, '@text.warning', { bg = '#e0af68', fg = '#1a1b26' })
vim.api.nvim_set_hl(0, '@text.note', { bg = '#0db9d7', fg = '#1a1b26' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { fg = '#e0af68', bg = '#16120a' })
vim.api.nvim_set_hl(0, 'healthError', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, '@text.reference', { fg = '#1abc9c' })
vim.api.nvim_set_hl(0, '@text.environment.name', { fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#292e42' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = '#16161e', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, '@text.environment', { fg = '#73daca' })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = '#210b0b' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#15161e' })
vim.api.nvim_set_hl(0, '@string.escape', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, '@string.regex', { fg = '#b4f9f8' })
vim.api.nvim_set_hl(0, 'rainbowcol4', { fg = '#1abc9c' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'WarningMsg', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'Operator', { fg = '#89ddff' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { fg = '#89ddff' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBody', { bg = '#1a1b26', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, '@property', { fg = '#73daca' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { bg = 'NONE', fg = '#2ac3de' })
vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { undercurl = true, sp = '#0db9d7' })
vim.api.nvim_set_hl(0, 'ModeMsg', { bold = true, fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'StatusLine', { bg = '#16161e', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, '@parameter', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, '@operator', { fg = '#89ddff' })
vim.api.nvim_set_hl(0, '@label', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { undercurl = true, sp = '#1abc9c' })
vim.api.nvim_set_hl(0, '@keyword.function', { italic = true, fg = '#bb9af7' })
vim.api.nvim_set_hl(0, '@keyword', { italic = true, fg = '#9d7cd8' })
vim.api.nvim_set_hl(0, 'NotifyDEBUGIcon', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'VisualNOS', { bg = '#2b3e71' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#15161e' })
vim.api.nvim_set_hl(0, '@field', { fg = '#73daca' })
vim.api.nvim_set_hl(0, 'NormalSB', { bg = '#16161e', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { bg = 'NONE', fg = '#73daca' })
vim.api.nvim_set_hl(0, 'Title', { bold = true, fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { bg = 'NONE', fg = '#73daca' })
vim.api.nvim_set_hl(0, 'rainbowcol5', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'LineNr', { fg = '#3b4261' })
vim.api.nvim_set_hl(0, '@constructor', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'NotifyINFOBody', { bg = '#1a1b26', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NotifyWARNBody', { bg = '#1a1b26', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'TabLineSel', { bg = '#7aa2f7', fg = '#15161e' })
vim.api.nvim_set_hl(0, 'NotifyERRORBody', { bg = '#1a1b26', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'CmpDocumentation', { bg = '#16161e', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'NotifyERRORTitle', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'MoreMsg', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'NotifyINFOIcon', { fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'NotifyWARNIcon', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'NotifyTRACEBorder', { bg = '#1a1b26', fg = '#2f2541' })
vim.api.nvim_set_hl(0, 'Search', { fg = '#c0caf5', bg = '#3d59a1' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { bg = 'NONE', fg = '#73daca' })
vim.api.nvim_set_hl(0, 'Statement', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'NotifyINFOBorder', { bg = '#1a1b26', fg = '#043841' })
vim.api.nvim_set_hl(0, 'NotifyWARNBorder', { bg = '#1a1b26', fg = '#43351f' })
vim.api.nvim_set_hl(0, 'NotifyERRORBorder', { bg = '#1a1b26', fg = '#421717' })
vim.api.nvim_set_hl(0, 'NeoTreeNormal', { bg = '#16161e', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { fg = '#536c9e' })
vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { fg = '#db4b4b', bg = '#160808' })
vim.api.nvim_set_hl(0, 'IndentBlanklineChar', { fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = '#0db9d7' })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { fg = '#266d6a' })
vim.api.nvim_set_hl(0, 'Todo', { fg = '#1a1b26', bg = '#e0af68' })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { bg = 'NONE', fg = '#737aa2' })
vim.api.nvim_set_hl(0, 'debugPC', { bg = '#16161e' })
vim.api.nvim_set_hl(0, 'CmpItemAbbr', { bg = 'NONE', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { bg = 'NONE', fg = '#73daca' })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { bg = 'NONE', fg = '#73daca' })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { bg = 'NONE', fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { bg = 'NONE', fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'CmpItemKindEvent', { bg = 'NONE', fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { bg = 'NONE', fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#2b3e71' })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', { bg = 'NONE', fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { fg = '#b2555b' })
vim.api.nvim_set_hl(0, '@punctuation.special.markdown', { bold = true, fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { bg = 'NONE', fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { bg = 'NONE', fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { bg = 'NONE', fg = '#bb9af7' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'CmpItemKindDefault', { bg = 'NONE', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { bg = 'NONE', fg = '#2ac3de' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'FloatBorder', { bg = '#16161e', fg = '#3d59a1' })
vim.api.nvim_set_hl(0, 'LeapLabelSecondary', { bold = true, fg = '#73daca' })
vim.api.nvim_set_hl(0, 'FoldColumn', { fg = '#565f89', bg = '#1a1b26' })
vim.api.nvim_set_hl(0, 'LeapLabelPrimary', { bold = true, fg = '#ff007c' })
vim.api.nvim_set_hl(0, 'Special', { fg = '#2ac3de' })
vim.api.nvim_set_hl(0, 'Type', { fg = '#2ac3de' })
vim.api.nvim_set_hl(0, 'CurSearch', { link = 'IncSearch' })
vim.api.nvim_set_hl(0, 'TelescopeBorder', { bg = '#16161e', fg = '#3d59a1' })
vim.api.nvim_set_hl(0, 'LeapMatch', { bg = '#ff007c', fg = '#c0caf5', bold = true })
vim.api.nvim_set_hl(0, 'healthWarning', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'LspSignatureActiveParameter', { fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'NeoTreeNormalNC', { bg = '#16161e', fg = '#a9b1d6' })
vim.api.nvim_set_hl(0, 'Pmenu', { fg = '#c0caf5', bg = '#16161e' })
vim.api.nvim_set_hl(0, 'qfLineNr', { fg = '#737aa2' })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', { bg = 'NONE', fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'rainbowcol6', { fg = '#bb9af7' })
vim.api.nvim_set_hl(0, '@punctuation.special', { fg = '#89ddff' })
vim.api.nvim_set_hl(0, 'LspInfoBorder', { bg = '#16161e', fg = '#3d59a1' })
vim.api.nvim_set_hl(0, 'LspCodeLens', { fg = '#565f89' })
vim.api.nvim_set_hl(0, 'WinSeparator', { bold = true, fg = '#15161e' })
vim.api.nvim_set_hl(0, 'SpellRare', { undercurl = true, sp = '#1abc9c' })
vim.api.nvim_set_hl(0, 'healthSuccess', { fg = '#73daca' })
vim.api.nvim_set_hl(0, '@preproc', { fg = '#e0af68' })
vim.api.nvim_set_hl(0, 'SignColumnSB', { fg = '#3b4261', bg = '#16161e' })
vim.api.nvim_set_hl(0, 'SignColumn', { fg = '#3b4261', bg = '#1a1b26' })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = '#3b4261' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { fg = '#9d7cd8' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = '#db4b4b' })
vim.api.nvim_set_hl(0, 'Underlined', { underline = true })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { bg = 'NONE', fg = '#7aa2f7' })
vim.api.nvim_set_hl(0, 'lCursor', { bg = '#c0caf5', fg = '#1a1b26' })
vim.api.nvim_set_hl(0, 'debugBreakpoint', { fg = '#0db9d7', bg = '#011316' })
vim.api.nvim_set_hl(0, 'Keyword', { fg = '#7dcfff' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#3b4261' })
vim.api.nvim_set_hl(0, 'WildMenu', { bg = '#2b3e71' })
vim.api.nvim_set_hl(0, 'NonText', { fg = '#545c7e' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { undercurl = true, sp = '#db4b4b' })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { bg = 'NONE', fg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'TabLine', { fg = '#3b4261', bg = '#16161e' })
vim.api.nvim_set_hl(0, 'IncSearch', { fg = '#15161e', bg = '#ff9e64' })
vim.api.nvim_set_hl(0, 'QuickFixLine', { bold = true, bg = '#2b3e71' })
vim.api.nvim_set_hl(0, 'TelescopeNormal', { bg = '#16161e', fg = '#c0caf5' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { undercurl = true, sp = '#e0af68' })
