vim.g.colors_name = 'vscode'

vim.g.terminal_color_15 = "#D4D4D4"
vim.g.terminal_color_13 = "#C586C0"
vim.g.terminal_color_7 = "#D4D4D4"
vim.g.terminal_color_14 = "#4EC9B0"
vim.g.terminal_color_9 = "#F44747"
vim.g.terminal_color_2 = "#6A9955"
vim.g.terminal_color_0 = "#1E1E1E"
vim.g.terminal_color_3 = "#DCDCAA"
vim.g.terminal_color_6 = "#4EC9B0"
vim.g.terminal_color_5 = "#C586C0"
vim.g.terminal_color_12 = "#569CD6"
vim.g.terminal_color_4 = "#569CD6"
vim.g.terminal_color_8 = "#808080"
vim.g.terminal_color_11 = "#DCDCAA"
vim.g.terminal_color_1 = "#F44747"
vim.g.terminal_color_10 = "#6A9955"

vim.api.nvim_set_hl(0, "@constant.builtin", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "@attribute", { fg = "#4EC9B0", bg = "NONE" })
vim.api.nvim_set_hl(0, "texBeginEndModifier", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "NonText", { fg = "#5A5A5A", bg = "NONE" })
vim.api.nvim_set_hl(0, "@label", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "WildMenu", { fg = "NONE", bg = "#264F78" })
vim.api.nvim_set_hl(0, "TelescopeMultiSelection", { fg = "#D4D4D4", bg = "#004b72" })
vim.api.nvim_set_hl(0, "Title", { bg = "NONE", fg = "NONE", bold = true })
vim.api.nvim_set_hl(0, "@namespace", { fg = "#4EC9B0", bg = "NONE" })
vim.api.nvim_set_hl(0, "@punctuation.delimiter", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "Exception", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpellLocal", { undercurl = true, sp = "#F44747", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "Visual", { fg = "NONE", bg = "#264F78" })
vim.api.nvim_set_hl(0, "Tag", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "GitSignsAdd", { fg = "#6A9955", bg = "NONE" })
vim.api.nvim_set_hl(0, "Normal", { fg = "#D4D4D4", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "MatchParen", { fg = "NONE", bg = "#51504F" })
vim.api.nvim_set_hl(0, "DiffText", { fg = "NONE", bg = "#6F1313" })
vim.api.nvim_set_hl(0, "ColorColumn", { fg = "NONE", bg = "#222222" })
vim.api.nvim_set_hl(0, "CmpItemKindText", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "Type", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "@repeat", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticError", { fg = "#F44747", bg = "NONE" })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#444444", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "@type.builtin", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "Folded", { fg = "NONE", bg = "#202d39" })
vim.api.nvim_set_hl(0, "@punctuation.bracket", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "Question", { fg = "#569CD6", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "@text.environment.name", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "MoreMsg", { fg = "#D4D4D4", bg = "#252526" })
vim.api.nvim_set_hl(0, "@text.title", { fg = "#569CD6", bold = true })
vim.api.nvim_set_hl(0, "@annotation", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "@punctuation.special", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "Macro", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "ErrorMsg", { fg = "#F44747", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "@function.macro.latex", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "Whitespace", { fg = "#5A5A5A" })
vim.api.nvim_set_hl(0, "@number", { fg = "#B5CEA8", bg = "NONE" })
vim.api.nvim_set_hl(0, "Constant", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text.emphasis", { bg = "NONE", fg = "#D4D4D4", italic = true })
vim.api.nvim_set_hl(0, "@variable.builtin", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpellRare", { undercurl = true, sp = "#F44747", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "texBeginEnd", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "TelescopePromptPrefix", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text.uri", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "TelescopeMatching", { bg = "NONE", fg = "#18a2fe", bold = true })
vim.api.nvim_set_hl(0, "TelescopeSelection", { fg = "#D4D4D4", bg = "#004b72" })
vim.api.nvim_set_hl(0, "TelescopeNormal", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text.strong", { fg = "#569CD6", bold = true })
vim.api.nvim_set_hl(0, "CmpItemKindOperator", { link = "@operator" })
vim.api.nvim_set_hl(0, "TelescopePromptBorder", { fg = "#5A5A5A", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpellCap", { undercurl = true, sp = "#F44747", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "Include", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "GitSignsAddLn", { fg = "#1E1E1E", bg = "#6A9955" })
vim.api.nvim_set_hl(0, "GitSignsDeleteLn", { fg = "#1E1E1E", bg = "#F44747" })
vim.api.nvim_set_hl(0, "@keyword.function", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "rainbowcol6", { fg = "#179FFF" })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "rainbowcol5", { fg = "#DA70D6" })
vim.api.nvim_set_hl(0, "rainbowcol4", { fg = "#FFD700" })
vim.api.nvim_set_hl(0, "CmpItemKindColor", { link = "cssColor" })
vim.api.nvim_set_hl(0, "@string.latex", { fg = "#4EC9B0", bg = "NONE" })
vim.api.nvim_set_hl(0, "ModeMsg", { fg = "#D4D4D4", bg = "#252526" })
vim.api.nvim_set_hl(0, "rainbowcol2", { fg = "#DA70D6" })
vim.api.nvim_set_hl(0, "Cursor", { fg = "#51504F", bg = "#AEAFAD" })
vim.api.nvim_set_hl(0, "rainbowcol1", { fg = "#FFD700" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "SignColumn", { fg = "NONE", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "Character", { fg = "#CE9178", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpecialKey", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "@method", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "@float", { fg = "#B5CEA8", bg = "NONE" })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#5A5A5A", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "CmpItemKindStruct", { link = "Structure" })
vim.api.nvim_set_hl(0, "Underlined", { underline = true, fg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#BBBBBB", bg = "#004b72" })
vim.api.nvim_set_hl(0, "Float", { fg = "#B5CEA8", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindConstant", { link = "@constant" })
vim.api.nvim_set_hl(0, "rainbowcol7", { fg = "#DA70D6" })
vim.api.nvim_set_hl(0, "texStatement", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "@type", { fg = "#4EC9B0", bg = "NONE" })
vim.api.nvim_set_hl(0, "@string.regex", { fg = "#CE9178", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineHint", { undercurl = true, sp = "#569CD6", fg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "@comment", { fg = "#6A9955", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindFile", { link = "@text.uri" })
vim.api.nvim_set_hl(0, "CmpItemKindSnippet", { link = "@text" })
vim.api.nvim_set_hl(0, "CmpItemKindEnum", { link = "@field" })
vim.api.nvim_set_hl(0, "TabLineSel", { fg = "#D4D4D4", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "NONE", bg = "#6F1313" })
vim.api.nvim_set_hl(0, "texOption", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "Special", { fg = "#D7BA7D", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindField", { link = "@field" })
vim.api.nvim_set_hl(0, "@property", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindValue", { link = "@field" })
vim.api.nvim_set_hl(0, "CmpItemKindUnit", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindReference", { link = "@parameter.reference" })
vim.api.nvim_set_hl(0, "CursorLineNr", { fg = "#BBBBBB", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "@character", { fg = "#CE9178", bg = "NONE" })
vim.api.nvim_set_hl(0, "String", { fg = "#CE9178", bg = "NONE" })
vim.api.nvim_set_hl(0, "TelescopeResultsBorder", { fg = "#5A5A5A", bg = "NONE" })
vim.api.nvim_set_hl(0, "TabLineFill", { fg = "#D4D4D4", bg = "#252526" })
vim.api.nvim_set_hl(0, "@keyword", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindClass", { link = "CmpItemKindConstructor" })
vim.api.nvim_set_hl(0, "CmpItemKind", { link = "Pmenu" })
vim.api.nvim_set_hl(0, "TelescopePreviewBorder", { fg = "#5A5A5A", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatch", { bg = "NONE", fg = "#18a2fe", bold = true })
vim.api.nvim_set_hl(0, "IncSearch", { fg = "NONE", bg = "#515c6a" })
vim.api.nvim_set_hl(0, "CmpItemAbbrDeprecated", { strikethrough = true, fg = "#51504F", bg = "#272727" })
vim.api.nvim_set_hl(0, "@constant", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "@operator", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "NONE", bg = "#4B1818" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemMenu", { fg = "#BBBBBB", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindConstructor", { fg = "#f28b25", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindEvent", { link = "@constant" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineError", { undercurl = true, sp = "#F44747", fg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "@constant.macro", { fg = "#4EC9B0", bg = "NONE" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "PmenuThumb", { fg = "NONE", bg = "#BBBBBB" })
vim.api.nvim_set_hl(0, "CursorLine", { bg = "#222222" })
vim.api.nvim_set_hl(0, "@keyword.operator", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "@conditional", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindKeyword", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindMethod", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "PmenuSbar", { fg = "NONE", bg = "#343B41" })
vim.api.nvim_set_hl(0, "@text.literal.markdown_inline", { fg = "#CE9178" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#BBBBBB", bg = "#272727" })
vim.api.nvim_set_hl(0, "@text.reference", { fg = "#CE9178" })
vim.api.nvim_set_hl(0, "CmpItemKindInterface", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpecialComment", { fg = "#6A9955", bg = "NONE" })
vim.api.nvim_set_hl(0, "FoldColumn", { fg = "#5A5A5A", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "LspReferenceWrite", { fg = "NONE", bg = "#343B41" })
vim.api.nvim_set_hl(0, "IndentBlanklineSpaceCharBlankline", { nocombine = true, fg = "#404040", bg = "NONE" })
vim.api.nvim_set_hl(0, "IndentBlanklineContextChar", { nocombine = true, fg = "#707070", bg = "NONE" })
vim.api.nvim_set_hl(0, "LspReferenceRead", { fg = "NONE", bg = "#343B41" })
vim.api.nvim_set_hl(0, "LspReferenceText", { fg = "NONE", bg = "#343B41" })
vim.api.nvim_set_hl(0, "Todo", { bg = "#1E1E1E", fg = "#D7BA7D", bold = true })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineInfo", { undercurl = true, sp = "#569CD6", fg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticUnderlineWarn", { undercurl = true, sp = "#DCDCAA", fg = "NONE", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text.environment", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "Directory", { fg = "#569CD6" })
vim.api.nvim_set_hl(0, "Search", { fg = "NONE", bg = "#613315" })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "@string.escape", { fg = "#CE9178", bold = true })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "IndentBlanklineContextStart", { nocombine = true, fg = "#707070", bg = "NONE" })
vim.api.nvim_set_hl(0, "IndentBlanklineChar", { nocombine = true, fg = "#404040", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindEnumMember", { link = "@field" })
vim.api.nvim_set_hl(0, "@text.math", { fg = "#4EC9B0", bg = "NONE" })
vim.api.nvim_set_hl(0, "GitSignsChangeLn", { fg = "#1E1E1E", bg = "#DCDCAA" })
vim.api.nvim_set_hl(0, "GitSignsDelete", { fg = "#F44747", bg = "NONE" })
vim.api.nvim_set_hl(0, "Define", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "Debug", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text.literal.markdown", { fg = "#CE9178" })
vim.api.nvim_set_hl(0, "texDocTypeArgs", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "Conceal", { fg = "#D4D4D4", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "CmpItemAbbr", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "SpellBad", { undercurl = true, sp = "#F44747", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "texBeginEndName", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "rainbowcol3", { fg = "#179FFF" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "NONE", bg = "#4B5632" })
vim.api.nvim_set_hl(0, "Label", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "@function.builtin", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "DiagnosticHint", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "EndOfBuffer", { fg = "#1E1E1E", bg = "NONE" })
vim.api.nvim_set_hl(0, "CursorColumn", { fg = "NONE", bg = "#222222" })
vim.api.nvim_set_hl(0, "@punctuation.special.markdown", { fg = "#569CD6", bold = true })
vim.api.nvim_set_hl(0, "CmpItemKindFunction", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text.danger", { bg = "NONE", fg = "#F44747", bold = true })
vim.api.nvim_set_hl(0, "@text.warning", { bg = "NONE", fg = "#D7BA7D", bold = true })
vim.api.nvim_set_hl(0, "@parameter", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#D4D4D4", bg = "#373737" })
vim.api.nvim_set_hl(0, "IndentBlanklineSpaceChar", { nocombine = true, fg = "#404040", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemAbbrMatchFuzzy", { bg = "NONE", fg = "#18a2fe", bold = true })
vim.api.nvim_set_hl(0, "@text.literal", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "@tag.delimiter", { fg = "#808080", bg = "NONE" })
vim.api.nvim_set_hl(0, "@tag", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text.underline", { fg = "#D7BA7D", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "@variable", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "@function.macro", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "Function", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "TabLine", { fg = "#8f8f8f", bg = "#2D2D2D" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "@include", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindProperty", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "@exception", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindModule", { link = "CmpItemKindKeyword" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "Comment", { fg = "#6A9955", bg = "NONE" })
vim.api.nvim_set_hl(0, "@field", { fg = "#4EC9B0", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindTypeParameter", { link = "@parameter" })
vim.api.nvim_set_hl(0, "@parameter.reference", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "@text.note", { bg = "NONE", fg = "#4EC9B0", bold = true })
vim.api.nvim_set_hl(0, "@error", { fg = "#F44747", bg = "NONE" })
vim.api.nvim_set_hl(0, "@string", { fg = "#CE9178", bg = "NONE" })
vim.api.nvim_set_hl(0, "@boolean", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "WarningMsg", { bg = "#1E1E1E", fg = "#F44747", bold = true })
vim.api.nvim_set_hl(0, "CmpItemKindFolder", { link = "@text.uri" })
vim.api.nvim_set_hl(0, "@function", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "Error", { undercurl = true, sp = "#F44747", fg = "#F44747", bg = "#1E1E1E" })
vim.api.nvim_set_hl(0, "Ignore", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "GitSignsChange", { fg = "#DCDCAA", bg = "NONE" })
vim.api.nvim_set_hl(0, "CmpItemKindVariable", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "StorageClass", { fg = "#569CD6", bg = "NONE" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#9CDCFE", bg = "NONE" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#D4D4D4", bg = "NONE" })
vim.api.nvim_set_hl(0, "texDocType", { fg = "#C586C0", bg = "NONE" })
vim.api.nvim_set_hl(0, "Number", { fg = "#B5CEA8", bg = "NONE" })
vim.api.nvim_set_hl(0, "@constructor", { fg = "#4EC9B0", bg = "NONE" })
vim.api.nvim_set_hl(0, "VisualNOS", { fg = "NONE", bg = "#264F78" })
vim.api.nvim_set_hl(0, "StatusLineNC", { fg = "#D4D4D4", bg = "#252526" })