vim.g.colors_name = 'vscode'
vim.g.skip_ts_default_groups = true
vim.o.termguicolors = true

vim.g.terminal_color_3 = '#DCDCAA'
vim.g.terminal_color_14 = '#4EC9B0'
vim.g.terminal_color_11 = '#DCDCAA'
vim.g.terminal_color_1 = '#F44747'
vim.g.terminal_color_7 = '#D4D4D4'
vim.g.terminal_color_2 = '#6A9955'
vim.g.terminal_color_6 = '#4EC9B0'
vim.g.terminal_color_10 = '#6A9955'
vim.g.terminal_color_8 = '#808080'
vim.g.terminal_color_13 = '#C586C0'
vim.g.terminal_color_5 = '#C586C0'
vim.g.terminal_color_0 = '#1E1E1E'
vim.g.terminal_color_4 = '#569CD6'
vim.g.terminal_color_12 = '#569CD6'
vim.g.terminal_color_15 = '#D4D4D4'
vim.g.terminal_color_9 = '#F44747'

vim.api.nvim_set_hl(0, 'Question', { bg = '#1E1E1E', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'Delimiter', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'texStatement', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, '@comment', { italic = true, bg = 'NONE', fg = '#6A9955' })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, '@constant', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, 'CmpItemKindConstructor', { bg = 'NONE', fg = '#f28b25' })
vim.api.nvim_set_hl(0, '@tag', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'Visual', { bg = '#264F78', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnumMember', { link = '@field' })
vim.api.nvim_set_hl(0, 'MoreMsg', { bg = '#252526', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'Directory', { fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'Label', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'Function', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, 'CmpItemAbbr', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'CmpItemKind', { link = 'Pmenu' })
vim.api.nvim_set_hl(0, 'Operator', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, '@keyword', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, 'PmenuSel', { bg = '#004b72', fg = '#BBBBBB' })
vim.api.nvim_set_hl(0, 'CmpItemKindStruct', { link = 'Structure' })
vim.api.nvim_set_hl(0, 'CursorLine', { bg = '#222222' })
vim.api.nvim_set_hl(0, 'Statement', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, '@constant.macro', { bg = 'NONE', fg = '#4EC9B0' })
vim.api.nvim_set_hl(0, '@keyword.operator', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'CmpItemKindKeyword', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'CompeDocumentation', { link = 'Pmenu' })
vim.api.nvim_set_hl(0, 'MatchParen', { bg = '#51504F', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Constant', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'ColorColumn', { bg = '#222222', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'CmpItemKindModule', { link = 'CmpItemKindKeyword' })
vim.api.nvim_set_hl(0, 'SpecialChar', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, '@string.escape', { bold = true, fg = '#CE9178' })
vim.api.nvim_set_hl(0, 'rainbowcol7', { fg = '#DA70D6' })
vim.api.nvim_set_hl(0, 'Include', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'CmpItemKindTypeParameter', { link = '@parameter' })
vim.api.nvim_set_hl(0, '@function.macro', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, 'CmpItemKindInterface', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, '@punctuation.special', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, '@text.literal', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'TabLineFill', { bg = '#252526', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { bg = 'NONE', fg = '#1E1E1E' })
vim.api.nvim_set_hl(0, 'Pmenu', { bg = '#272727', fg = '#BBBBBB' })
vim.api.nvim_set_hl(0, 'Type', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'Cursor', { bg = '#AEAFAD', fg = '#51504F' })
vim.api.nvim_set_hl(0, 'CursorColumn', { bg = '#222222', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Search', { bg = '#613315', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Todo', { bold = true, bg = '#1E1E1E', fg = '#D7BA7D' })
vim.api.nvim_set_hl(0, 'CmpItemKindField', { link = '@field' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineWarn', { sp = '#DCDCAA', bg = 'NONE', undercurl = true, fg = 'NONE' })
vim.api.nvim_set_hl(0, 'CmpItemKindFolder', { link = '@text.uri' })
vim.api.nvim_set_hl(0, 'SpellLocal', { sp = '#F44747', undercurl = true, bg = '#1E1E1E' })
vim.api.nvim_set_hl(0, 'CmpItemKindReference', { link = '@parameter.reference' })
vim.api.nvim_set_hl(0, 'Title', { bold = true, bg = 'NONE', fg = 'NONE' })
vim.api.nvim_set_hl(0, '@method', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, 'GitSignsAdd', { bg = 'NONE', fg = '#6A9955' })
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceChar', { nocombine = true, bg = 'NONE', fg = '#404040' })
vim.api.nvim_set_hl(0, 'DiagnosticError', { bg = 'NONE', fg = '#F44747' })
vim.api.nvim_set_hl(0, 'Tag', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'LineNr', { bg = '#1E1E1E', fg = '#5A5A5A' })
vim.api.nvim_set_hl(0, 'CompeDocumentationBorder', { link = 'Pmenu' })
vim.api.nvim_set_hl(0, '@error', { bg = 'NONE', fg = '#F44747' })
vim.api.nvim_set_hl(0, 'CmpItemKindUnit', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'texDocTypeArgs', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, 'Normal', { bg = '#1E1E1E', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'Special', { bg = 'NONE', fg = '#D7BA7D' })
vim.api.nvim_set_hl(0, 'Define', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'Debug', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'texDocType', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, '@function', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, 'CmpItemKindMethod', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'LspReferenceRead', { bg = '#343B41', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Conceal', { bg = '#1E1E1E', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'DiffAdd', { bg = '#4B5632', fg = 'NONE' })
vim.api.nvim_set_hl(0, '@text.literal.markdown', { fg = '#CE9178' })
vim.api.nvim_set_hl(0, 'texBeginEndName', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, 'GitSignsChangeLn', { bg = '#DCDCAA', fg = '#1E1E1E' })
vim.api.nvim_set_hl(0, 'CmpItemKindProperty', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'StorageClass', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'GitSignsChange', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, 'texBeginEnd', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, '@character', { bg = 'NONE', fg = '#CE9178' })
vim.api.nvim_set_hl(0, 'texOption', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, '@variable', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, 'Float', { bg = 'NONE', fg = '#B5CEA8' })
vim.api.nvim_set_hl(0, '@text.literal.markdown_inline', { fg = '#CE9178' })
vim.api.nvim_set_hl(0, '@variable.builtin', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, '@text.note', { bold = true, bg = 'NONE', fg = '#4EC9B0' })
vim.api.nvim_set_hl(0, '@text.warning', { bold = true, bg = 'NONE', fg = '#D7BA7D' })
vim.api.nvim_set_hl(0, '@namespace', { bg = 'NONE', fg = '#4EC9B0' })
vim.api.nvim_set_hl(0, 'rainbowcol5', { fg = '#DA70D6' })
vim.api.nvim_set_hl(0, '@text.underline', { bg = 'NONE', fg = '#D7BA7D' })
vim.api.nvim_set_hl(0, '@punctuation.delimiter', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'Error', { sp = '#F44747', bg = '#1E1E1E', undercurl = true, fg = '#F44747' })
vim.api.nvim_set_hl(0, 'CmpItemKindConstant', { link = '@constant' })
vim.api.nvim_set_hl(0, '@parameter.reference', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, 'GitSignsDelete', { bg = 'NONE', fg = '#F44747' })
vim.api.nvim_set_hl(0, 'PreProc', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'CmpItemKindSnippet', { link = '@text' })
vim.api.nvim_set_hl(0, '@text.emphasis', { italic = true, bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'Boolean', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = '#1E1E1E', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Conditional', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'rainbowcol3', { fg = '#179FFF' })
vim.api.nvim_set_hl(0, '@text.title', { bold = true, fg = '#569CD6' })
vim.api.nvim_set_hl(0, '@tag.delimiter', { bg = 'NONE', fg = '#808080' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatch', { bold = true, bg = 'NONE', fg = '#18a2fe' })
vim.api.nvim_set_hl(0, '@text', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, '@text.danger', { bold = true, bg = 'NONE', fg = '#F44747' })
vim.api.nvim_set_hl(0, 'IncSearch', { bg = '#515c6a', fg = 'NONE' })
vim.api.nvim_set_hl(0, '@include', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'Whitespace', { fg = '#5A5A5A' })
vim.api.nvim_set_hl(0, 'Structure', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'CursorLineNr', { bg = '#1E1E1E', fg = '#BBBBBB' })
vim.api.nvim_set_hl(0, 'CmpItemKindOperator', { link = '@operator' })
vim.api.nvim_set_hl(0, 'NonText', { bg = 'NONE', fg = '#5A5A5A' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { bg = '#1E1E1E', fg = '#F44747' })
vim.api.nvim_set_hl(0, 'IndentBlanklineChar', { nocombine = true, bg = 'NONE', fg = '#404040' })
vim.api.nvim_set_hl(0, 'rainbowcol6', { fg = '#179FFF' })
vim.api.nvim_set_hl(0, '@keyword.function', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, '@repeat', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'Keyword', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, '@constructor', { bg = 'NONE', fg = '#4EC9B0' })
vim.api.nvim_set_hl(0, '@property', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, '@field', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, '@parameter', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, '@text.uri', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'WarningMsg', { bold = true, bg = '#1E1E1E', fg = '#F44747' })
vim.api.nvim_set_hl(0, 'TabLineSel', { bg = '#1E1E1E', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'texBeginEndModifier', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, '@function.builtin', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, '@attribute', { bg = 'NONE', fg = '#4EC9B0' })
vim.api.nvim_set_hl(0, '@annotation', { bg = 'NONE', fg = '#DCDCAA' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrDeprecated', { strikethrough = true, bg = '#272727', fg = '#51504F' })
vim.api.nvim_set_hl(0, 'Repeat', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'CmpItemKindEnum', { link = '@field' })
vim.api.nvim_set_hl(0, '@boolean', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'SpecialKey', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'rainbowcol1', { fg = '#FFD700' })
vim.api.nvim_set_hl(0, 'Folded', { bg = '#202d39', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Underlined', { underline = true, bg = 'NONE', fg = 'NONE' })
vim.api.nvim_set_hl(0, '@punctuation.special.markdown', { bold = true, fg = '#569CD6' })
vim.api.nvim_set_hl(0, '@string', { bg = 'NONE', fg = '#CE9178' })
vim.api.nvim_set_hl(0, '@string.regex', { bg = 'NONE', fg = '#CE9178' })
vim.api.nvim_set_hl(0, '@constant.builtin', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextStart', { nocombine = true, bg = 'NONE', fg = '#707070' })
vim.api.nvim_set_hl(0, '@label', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineInfo', { sp = '#569CD6', bg = 'NONE', undercurl = true, fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Exception', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'FoldColumn', { bg = '#1E1E1E', fg = '#5A5A5A' })
vim.api.nvim_set_hl(0, 'rainbowcol4', { fg = '#FFD700' })
vim.api.nvim_set_hl(0, 'LspReferenceWrite', { bg = '#343B41', fg = 'NONE' })
vim.api.nvim_set_hl(0, '@conditional', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'IndentBlanklineSpaceCharBlankline', { nocombine = true, bg = 'NONE', fg = '#404040' })
vim.api.nvim_set_hl(0, 'TabLine', { bg = '#2D2D2D', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, '@operator', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'SpellBad', { sp = '#F44747', undercurl = true, bg = '#1E1E1E' })
vim.api.nvim_set_hl(0, '@punctuation.bracket', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'CmpItemKindValue', { link = '@field' })
vim.api.nvim_set_hl(0, 'GitSignsDeleteLn', { bg = '#F44747', fg = '#1E1E1E' })
vim.api.nvim_set_hl(0, 'CmpItemKindFunction', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'Comment', { italic = true, bg = 'NONE', fg = '#6A9955' })
vim.api.nvim_set_hl(0, 'Number', { bg = 'NONE', fg = '#B5CEA8' })
vim.api.nvim_set_hl(0, 'DiffDelete', { bg = '#6F1313', fg = 'NONE' })
vim.api.nvim_set_hl(0, '@text.reference', { fg = '#CE9178' })
vim.api.nvim_set_hl(0, 'Macro', { bg = 'NONE', fg = '#C586C0' })
vim.api.nvim_set_hl(0, 'CmpItemKindFile', { link = '@text.uri' })
vim.api.nvim_set_hl(0, 'CmpItemKindColor', { link = 'cssColor' })
vim.api.nvim_set_hl(0, 'String', { bg = 'NONE', fg = '#CE9178' })
vim.api.nvim_set_hl(0, '@text.strong', { bold = true, fg = '#569CD6' })
vim.api.nvim_set_hl(0, '@float', { bg = 'NONE', fg = '#B5CEA8' })
vim.api.nvim_set_hl(0, 'StatusLineNC', { bg = '#252526', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { nocombine = true, bg = 'NONE', fg = '#707070' })
vim.api.nvim_set_hl(0, '@type', { bg = 'NONE', fg = '#4EC9B0' })
vim.api.nvim_set_hl(0, 'CmpItemKindClass', { link = 'CmpItemKindConstructor' })
vim.api.nvim_set_hl(0, 'CmpItemAbbrMatchFuzzy', { bold = true, bg = 'NONE', fg = '#18a2fe' })
vim.api.nvim_set_hl(0, 'PmenuSbar', { bg = '#343B41', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'CmpItemMenu', { bg = 'NONE', fg = '#BBBBBB' })
vim.api.nvim_set_hl(0, 'CmpItemKindText', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, 'CmpItemKindVariable', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, 'SpecialComment', { bg = 'NONE', fg = '#6A9955' })
vim.api.nvim_set_hl(0, '@type.builtin', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'WildMenu', { bg = '#264F78', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Ignore', { bg = 'NONE', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'DiffChange', { bg = '#4B1818', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'SpellRare', { sp = '#F44747', undercurl = true, bg = '#1E1E1E' })
vim.api.nvim_set_hl(0, 'SpellCap', { sp = '#F44747', undercurl = true, bg = '#1E1E1E' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineError', { sp = '#F44747', bg = 'NONE', undercurl = true, fg = 'NONE' })
vim.api.nvim_set_hl(0, '@number', { bg = 'NONE', fg = '#B5CEA8' })
vim.api.nvim_set_hl(0, 'LspReferenceText', { bg = '#343B41', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Typedef', { bg = 'NONE', fg = '#569CD6' })
vim.api.nvim_set_hl(0, 'DiagnosticUnderlineHint', { sp = '#569CD6', bg = 'NONE', undercurl = true, fg = 'NONE' })
vim.api.nvim_set_hl(0, 'CmpItemKindEvent', { link = '@constant' })
vim.api.nvim_set_hl(0, 'VertSplit', { bg = '#1E1E1E', fg = '#444444' })
vim.api.nvim_set_hl(0, 'rainbowcol2', { fg = '#DA70D6' })
vim.api.nvim_set_hl(0, 'VisualNOS', { bg = '#264F78', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'Identifier', { bg = 'NONE', fg = '#9CDCFE' })
vim.api.nvim_set_hl(0, 'GitSignsAddLn', { bg = '#6A9955', fg = '#1E1E1E' })
vim.api.nvim_set_hl(0, 'Character', { bg = 'NONE', fg = '#CE9178' })
vim.api.nvim_set_hl(0, 'StatusLine', { bg = '#373737', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, 'DiffText', { bg = '#6F1313', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'PmenuThumb', { bg = '#BBBBBB', fg = 'NONE' })
vim.api.nvim_set_hl(0, 'ModeMsg', { bg = '#252526', fg = '#D4D4D4' })
vim.api.nvim_set_hl(0, '@exception', { bg = 'NONE', fg = '#C586C0' })
