require 'configs.cmp'
require 'configs.comment'
-- require 'configs.copilot'
require 'configs.fidget'
require 'configs.gitsigns'
require 'configs.indentline'
require 'configs.luasnip'
-- require 'configs.neorg'
require 'configs.outline'
require 'configs.pairs'
-- require 'configs.session'
require 'configs.telescope'
require 'configs.terminal'
require 'configs.tree'
require 'configs.treesitter'
require 'configs.vimtex'

require 'lsp'
require 'lsp.null-ls'
