return {
	"nvim-treesitter/nvim-treesitter",
	-- branch = "main",
	-- lazy = false,
	main = "nvim-treesitter.configs",
	event = { "BufReadPost", "BufNewFile" },
	build = ":TSUpdate",
	opts = {
		ensure_installed = {
			"bash",
			"bibtex",
			"c",
			"diff",
			"fish",
			"git_rebase",
			"gitcommit",
			"gitignore",
			"latex",
			"lua",
			"luadoc",
			"luap",
			"markdown",
			"markdown_inline",
			"matlab",
			"norg",
			"python",
			"query",
			"regex",
			"swift",
			"vim",
			"vimdoc",
		},
		highlight = { enable = true },
		incremental_selection = { enable = true },
		indent = { enable = true },
	},
}
